// Generated by tools/build-examples.mjs — do not edit by hand.
// Scans Examples/<Category>/*.json and lists them here so the Examples
// dropdown can fetch them at runtime without a directory listing (this is a
// static site). Re-run the generator after adding/removing/renaming a file
// under Examples/. Each entry's `slug` is a stable id used by the
// `?example=<slug>` demo boot (see main.js) and by
// tools/build-examples-pages.mjs's generated pages.
export const examples = [
  {
    "group": null,
    "name": "OPTICAL SETUP — pulsed component panorama",
    "path": "../Examples/OPTICAL%20SETUP%20%E2%80%94%20pulsed%20component%20panorama.json",
    "slug": "optical-setup-pulsed-component-panorama"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Array optics models",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Array%20optics%20models.json",
    "slug": "2pp-array-optics-models"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Buckmann 2014",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Buckmann%202014.json",
    "slug": "2pp-buckmann-2014"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Fischer 2011",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Fischer%202011.json",
    "slug": "2pp-fischer-2011"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Geng 2019",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Geng%202019.json",
    "slug": "2pp-geng-2019"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Gittard 2011",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Gittard%202011.json",
    "slug": "2pp-gittard-2011"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Gu 2025 129500 foci",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Gu%202025%20129500%20foci.json",
    "slug": "2pp-gu-2025-129500-foci"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Gu 2025 2500 foci",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Gu%202025%202500%20foci.json",
    "slug": "2pp-gu-2025-2500-foci"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Hahn 2020",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Hahn%202020.json",
    "slug": "2pp-hahn-2020"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Jiao 2023",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Jiao%202023.json",
    "slug": "2pp-jiao-2023"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Kiefer 2024",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Kiefer%202024.json",
    "slug": "2pp-kiefer-2024"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Nanoscribe Gt",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Nanoscribe%20Gt.json",
    "slug": "2pp-nanoscribe-gt"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Ouyang 2023",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Ouyang%202023.json",
    "slug": "2pp-ouyang-2023"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Pearre 2018",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Pearre%202018.json",
    "slug": "2pp-pearre-2018"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Saha 2019",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Saha%202019.json",
    "slug": "2pp-saha-2019"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Somers 2021",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Somers%202021.json",
    "slug": "2pp-somers-2021"
  },
  {
    "group": "2PP Paper Collection",
    "name": "2PP Zhang 2024",
    "path": "../Examples/2PP%20Paper%20Collection/2PP%20Zhang%202024.json",
    "slug": "2pp-zhang-2024"
  },
  {
    "group": "Lens Physics",
    "name": "Singlet vs achromat — axial colour",
    "path": "../Examples/Lens%20Physics/Singlet%20vs%20achromat%20%E2%80%94%20axial%20colour.json",
    "slug": "singlet-vs-achromat-axial-colour"
  },
  {
    "group": "Lens Physics",
    "name": "Spherical aberration — ideal lens vs spherical singlet",
    "path": "../Examples/Lens%20Physics/Spherical%20aberration%20%E2%80%94%20ideal%20lens%20vs%20spherical%20singlet.json",
    "slug": "spherical-aberration-ideal-lens-vs-spherical-singlet"
  },
  {
    "group": "Lens Physics",
    "name": "Spherical aberration — sphere vs asphere vs ideal lens",
    "path": "../Examples/Lens%20Physics/Spherical%20aberration%20%E2%80%94%20sphere%20vs%20asphere%20vs%20ideal%20lens.json",
    "slug": "spherical-aberration-sphere-vs-asphere-vs-ideal-lens"
  },
  {
    "group": "Microscopy Implementations",
    "name": "Coherent Raman microscope — SRS and CARS",
    "path": "../Examples/Microscopy%20Implementations/Coherent%20Raman%20microscope%20%E2%80%94%20SRS%20and%20CARS.json",
    "slug": "coherent-raman-microscope-srs-and-cars"
  },
  {
    "group": "Microscopy Implementations",
    "name": "Multiphoton microscope — SHG and two photon fluorescence",
    "path": "../Examples/Microscopy%20Implementations/Multiphoton%20microscope%20%E2%80%94%20SHG%20and%20two%20photon%20fluorescence.json",
    "slug": "multiphoton-microscope-shg-and-two-photon-fluorescence"
  },
  {
    "group": "Optics Bench",
    "name": "Mach–Zehnder interferometer",
    "path": "../Examples/Optics%20Bench/Mach%E2%80%93Zehnder%20interferometer.json",
    "slug": "mach-zehnder-interferometer"
  },
  {
    "group": "Optics Bench",
    "name": "Michelson interferometer",
    "path": "../Examples/Optics%20Bench/Michelson%20interferometer.json",
    "slug": "michelson-interferometer"
  },
  {
    "group": "Ultrashort Pulses",
    "name": "Ultrashort pulse chirping",
    "path": "../Examples/Ultrashort%20Pulses/Ultrashort%20pulse%20chirping.json",
    "slug": "ultrashort-pulse-chirping"
  }
];
