// Generated by tools/build-examples.mjs — do not edit by hand.
// Scans Examples/<Category>/*.json and lists them here so the Examples
// dropdown can fetch them at runtime without a directory listing (this is a
// static site). Re-run the generator after adding/removing/renaming a file
// under Examples/. Each entry's `slug` is a stable id used by the
// `?example=<slug>` demo boot (see main.js) and by
// tools/build-examples-pages.mjs's generated pages.
export const examples = [
  {
    "group": null,
    "name": "OPTICAL SETUP — pulsed component panorama",
    "path": "../Examples/OPTICAL%20SETUP%20%E2%80%94%20pulsed%20component%20panorama.json",
    "slug": "optical-setup-pulsed-component-panorama"
  },
  {
    "group": "Lens Physics",
    "name": "Singlet vs achromat — axial colour",
    "path": "../Examples/Lens%20Physics/Singlet%20vs%20achromat%20%E2%80%94%20axial%20colour.json",
    "slug": "singlet-vs-achromat-axial-colour"
  },
  {
    "group": "Lens Physics",
    "name": "Spherical aberration — ideal lens vs spherical singlet",
    "path": "../Examples/Lens%20Physics/Spherical%20aberration%20%E2%80%94%20ideal%20lens%20vs%20spherical%20singlet.json",
    "slug": "spherical-aberration-ideal-lens-vs-spherical-singlet"
  },
  {
    "group": "Lens Physics",
    "name": "Spherical aberration — sphere vs asphere vs ideal lens",
    "path": "../Examples/Lens%20Physics/Spherical%20aberration%20%E2%80%94%20sphere%20vs%20asphere%20vs%20ideal%20lens.json",
    "slug": "spherical-aberration-sphere-vs-asphere-vs-ideal-lens"
  },
  {
    "group": "Microscopy Implementations",
    "name": "Coherent Raman microscope — SRS and CARS",
    "path": "../Examples/Microscopy%20Implementations/Coherent%20Raman%20microscope%20%E2%80%94%20SRS%20and%20CARS.json",
    "slug": "coherent-raman-microscope-srs-and-cars"
  },
  {
    "group": "Microscopy Implementations",
    "name": "Multiphoton microscope — SHG and two photon fluorescence",
    "path": "../Examples/Microscopy%20Implementations/Multiphoton%20microscope%20%E2%80%94%20SHG%20and%20two%20photon%20fluorescence.json",
    "slug": "multiphoton-microscope-shg-and-two-photon-fluorescence"
  },
  {
    "group": "Nonlinear Optics",
    "name": "Near infrared supercontinuum in YAG",
    "path": "../Examples/Nonlinear%20Optics/Near%20infrared%20supercontinuum%20in%20YAG.json",
    "slug": "near-infrared-supercontinuum-in-yag"
  },
  {
    "group": "Nonlinear Optics",
    "name": "Optical parametric oscillator — ring cavity, element by element",
    "path": "../Examples/Nonlinear%20Optics/Optical%20parametric%20oscillator%20%E2%80%94%20ring%20cavity%2C%20element%20by%20element.json",
    "slug": "optical-parametric-oscillator-ring-cavity-element-by-element"
  },
  {
    "group": "Nonlinear Optics",
    "name": "Synchronously pumped picosecond OPO",
    "path": "../Examples/Nonlinear%20Optics/Synchronously%20pumped%20picosecond%20OPO.json",
    "slug": "synchronously-pumped-picosecond-opo"
  },
  {
    "group": "Optics Bench",
    "name": "Mach–Zehnder interferometer",
    "path": "../Examples/Optics%20Bench/Mach%E2%80%93Zehnder%20interferometer.json",
    "slug": "mach-zehnder-interferometer"
  },
  {
    "group": "Optics Bench",
    "name": "Michelson interferometer",
    "path": "../Examples/Optics%20Bench/Michelson%20interferometer.json",
    "slug": "michelson-interferometer"
  },
  {
    "group": "Reflective Imaging Systems",
    "name": "Gregorian telescope — element by element",
    "path": "../Examples/Reflective%20Imaging%20Systems/Gregorian%20telescope%20%E2%80%94%20element%20by%20element.json",
    "slug": "gregorian-telescope-element-by-element"
  },
  {
    "group": "Reflective Imaging Systems",
    "name": "IR Cassegrain objective — element by element",
    "path": "../Examples/Reflective%20Imaging%20Systems/IR%20Cassegrain%20objective%20%E2%80%94%20element%20by%20element.json",
    "slug": "ir-cassegrain-objective-element-by-element"
  },
  {
    "group": "Reflective Imaging Systems",
    "name": "Ritchey–Chrétien telescope — element by element",
    "path": "../Examples/Reflective%20Imaging%20Systems/Ritchey%E2%80%93Chr%C3%A9tien%20telescope%20%E2%80%94%20element%20by%20element.json",
    "slug": "ritchey-chretien-telescope-element-by-element"
  },
  {
    "group": "Scanning",
    "name": "Polygon scanner — line scanning",
    "path": "../Examples/Scanning/Polygon%20scanner%20%E2%80%94%20line%20scanning.json",
    "slug": "polygon-scanner-line-scanning"
  },
  {
    "group": "Ultrashort Pulses",
    "name": "Finding time zero — sum frequency of two beams",
    "path": "../Examples/Ultrashort%20Pulses/Finding%20time%20zero%20%E2%80%94%20sum%20frequency%20of%20two%20beams.json",
    "slug": "finding-time-zero-sum-frequency-of-two-beams"
  },
  {
    "group": "Ultrashort Pulses",
    "name": "Hollow core pulse compressor",
    "path": "../Examples/Ultrashort%20Pulses/Hollow-core%20pulse%20compressor.json",
    "slug": "hollow-core-pulse-compressor"
  },
  {
    "group": "Ultrashort Pulses",
    "name": "Marvel ATLAS laser — public architecture",
    "path": "../Examples/Ultrashort%20Pulses/Marvel%20ATLAS%20laser%20%E2%80%94%20public%20architecture.json",
    "slug": "marvel-atlas-laser-public-architecture"
  },
  {
    "group": "Ultrashort Pulses",
    "name": "Ultrashort pulse chirping",
    "path": "../Examples/Ultrashort%20Pulses/Ultrashort%20pulse%20chirping.json",
    "slug": "ultrashort-pulse-chirping"
  }
];
