// What the beam probe reports, separated from how it draws. Each function
// takes a probe reading (raytrace.js probeAt) and returns a number or a label,
// so the rules can be tested without an SVG or a DOM.

import { spectrumSamples } from './spectrum.js';

// The probe sits on one ray, which launches at intensity 1 and is multiplied
// down by everything it passes through. Every ray of a uniform beam is
// attenuated identically, so that surviving fraction is also the fraction of
// the beam's power still present -- and the source's configured average power
// times that fraction is the power here.
export function probeAveragePowerW(reading, elements = []) {
  if (!reading?.sourceId) return null;
  const source = elements.find(el => el?.id === reading.sourceId);
  const configured = Number(source?.params?.avgPowerW);
  if (!Number.isFinite(configured) || configured < 0) return null;
  const fraction = Number(reading.intensity);
  if (!Number.isFinite(fraction) || fraction < 0) return null;
  return configured * fraction;
}

export function formatPowerMw(watts) {
  if (!Number.isFinite(watts)) return '—';
  const mw = watts * 1000;
  if (mw === 0) return '0 mW';
  if (mw >= 1000) return `${(mw / 1000).toPrecision(3)} W`;
  if (mw >= 1) return `${mw.toPrecision(3)} mW`;
  if (mw >= 1e-3) return `${(mw * 1000).toPrecision(3)} µW`;
  return `${mw.toExponential(1)} mW`;
}

// A supercontinuum has no single pulse duration to report: its spectrum spans
// hundreds of nanometres generated by nonlinear broadening, and the app does
// not model the temporal structure that comes out of that. Saying "undefined"
// is the honest answer; quoting the train's nominal width would not be.
export function probeDurationLabel(reading, sourceType) {
  if (!reading) return '—';
  if (sourceType === 'sclaser') return 'Undefined';
  if (!reading.pulse) return 'CW source';
  const fs = Number(reading.pulse.pulseWidthFs);
  if (!Number.isFinite(fs) || fs <= 0) return 'Undefined';
  if (fs >= 1e6) return `${(fs / 1e6).toPrecision(3)} ns`;
  if (fs >= 1000) return `${(fs / 1000).toPrecision(3)} ps`;
  return `${fs < 100 ? fs.toPrecision(3) : Math.round(fs)} fs`;
}

// The slowest period on a beam, in ns: the repetition period, or a slower
// intensity modulation riding on it. Accepts either shape of pulse record --
// the probe's single train, or a detector's aggregate with its trains array --
// because both displays answer the same question about the same light.
export function slowestPeriodNs(pulse) {
  if (!pulse) return 0;
  const trains = Array.isArray(pulse.trains) && pulse.trains.length ? pulse.trains : [pulse];
  const rates = trains.map(t => Number(t?.repRateMHz)).filter(r => Number.isFinite(r) && r > 0);
  const repPeriod = rates.length ? Math.max(...rates.map(r => 1000 / r)) : 0;
  const gatePeriods = trains
    .flatMap(t => (Array.isArray(t?.gates) ? t.gates : []))
    .map(g => Number(g?.frequencyMHz))
    .filter(f => Number.isFinite(f) && f > 0)
    .map(f => 1000 / f);
  return Math.max(repPeriod, ...(gatePeriods.length ? gatePeriods : [0]));
}

// A signed time-axis label that stays readable from picoseconds to
// milliseconds without ever falling back to exponent notation -- a chopper
// runs at kilohertz while the train it gates runs at megahertz, so one axis
// has to cross six orders of magnitude.
export function formatTimeAxisNs(ns) {
  if (!Number.isFinite(ns) || ns === 0) return '0';
  const abs = Math.abs(ns);
  const [value, unit] = abs >= 1e6 ? [ns / 1e6, 'ms']
    : abs >= 1000 ? [ns / 1000, 'µs']
      : abs >= 1 ? [ns, 'ns']
        : [ns * 1000, 'ps'];
  const rounded = Math.abs(value) >= 100 ? Math.round(value) : Number(value.toPrecision(3));
  return `${rounded} ${unit}`;
}

// The default time window: two periods of the slowest thing happening on this
// beam. With nothing but the train itself that is two repetition periods, so
// three pulses land on screen; with an intensity modulation on top, it is two
// periods of the modulation, which is the thing you actually want to see.
export function probeTimeWindowNs(reading, params = {}) {
  const manual = Number(params.timeSpanNs);
  const offset = Number(params.timeOffsetNs);
  const startNs = Number.isFinite(offset) ? offset : 0;
  if (Number.isFinite(manual) && manual > 0) return { startNs, spanNs: manual, auto: false };
  const slowest = slowestPeriodNs(reading?.pulse);
  // A CW beam with no modulation at all has no timescale of its own; a
  // nanosecond of flat line is as good a window as any other.
  return { startNs, spanNs: slowest > 0 ? 2 * slowest : 1, auto: true };
}

// One window for a group of detectors, so their traces can be read against
// each other. It is the widest window any member would have picked alone, at
// the earliest offset any member asked for -- which guarantees nothing a
// member wanted to show falls outside the shared axis, and makes the result
// independent of which detector you happen to be drawing. Moving the offset
// on any one of them moves the whole group, which is what sync should feel
// like.
export function syncedTimeWindowNs(members) {
  const windows = (members || [])
    .map(m => probeTimeWindowNs(m?.reading, m?.params || {}))
    .filter(Boolean);
  if (!windows.length) return null;
  return {
    startNs: Math.min(...windows.map(w => w.startNs)),
    spanNs: Math.max(...windows.map(w => w.spanNs)),
    synced: true,
    members: windows.length,
  };
}

// The wavelength axis, on the spectrometer's own principle: span whatever
// clears a thousandth of the peak, rather than a fixed number of standard
// deviations, so a narrow line and a broad band are both framed by what they
// actually contain.
const DISPLAY_FLOOR = 1e-3;
const MIN_SPAN_NM = 10;

export function probeSpectrumRange(reading, params = {}) {
  const lo = Number(params.specMin), hi = Number(params.specMax);
  if (params.rangeMode === 'manual' && Number.isFinite(lo) && Number.isFinite(hi) && hi > lo) {
    return { lo, hi, auto: false };
  }
  const centre = Number(reading?.wl) || 0;
  const samples = reading?.spec ? (spectrumSamples(reading.spec, 96) || []) : [];
  const peak = samples.reduce((best, s) => Math.max(best, s.weight || 0), 0);
  const above = peak > 0 ? samples.filter(s => s.weight >= peak * DISPLAY_FLOOR) : [];
  if (!above.length) {
    // No sampled spectrum: a bare line, framed by its own bandwidth.
    const half = Math.max(MIN_SPAN_NM / 2, (Number(reading?.bw) || 0));
    return { lo: centre - half, hi: centre + half, auto: true };
  }
  let low = Math.min(...above.map(s => s.wl));
  let high = Math.max(...above.map(s => s.wl));
  const pad = Math.max(0.5, (high - low) * 0.06);
  low -= pad; high += pad;
  if (high - low < MIN_SPAN_NM) {
    const mid = (low + high) / 2;
    low = mid - MIN_SPAN_NM / 2; high = mid + MIN_SPAN_NM / 2;
  }
  return { lo: low, hi: high, auto: true };
}
