// Auto-generated by tools/build-wiki.mjs from wiki-content.mjs — do not edit by hand.
// Lists every component type that has a built page under wiki/, so the inspector
// can avoid linking to a page that doesn't exist yet.
export const WIKI_TYPES = new Set(["aod","aom","aotf","barefiber","beamdump","blocker","bs","camera","cmirror","cmirrorx","cwlaser","detector","dichroic","diffuser","dm","dmd","eom","etalon","fiber","filter","freeglass","galvo","glassrod","grating","hwp","isolator","lens","lensc","lensgroup","metalens","metasurface","mirror","oap","objective","pbs","phaseplate","pmt","polarimeter","polarizer","powermeter","prism","pulsecompressor","pulsedlaser","qwp","retroreflector","sclaser","slit","slm","spectrometer","telescope","thicklens","vipa","wavefrontdetector"]);
