// SPDX-FileCopyrightText: 2026 Luca Genchi and contributors
// SPDX-License-Identifier: GPL-3.0-or-later
import { createElement } from '../../sketch/js/elements.js';

const ref = (label, url) => ({ label, url });
const conjugates = ref('Nikon: conjugate planes in optical microscopy', 'https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy');
const expanders = ref('Edmund Optics: laser beam expanders', 'https://www.edmundoptics.com/knowledge-center/application-notes/lasers/beam-expanders');
const telecentric = ref('Edmund Optics: distortion and telecentricity', 'https://www.edmundoptics.com/knowledge-center/application-notes/imaging/distortion-and-the-telecentricity-specification/');
const plates = ref('Thorlabs: waveplate tutorial', 'https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7234&tabname=Tutorial');
const coherent = ref('Thorlabs: balanced coherent detection application note', 'https://www.thorlabs.com/images/tabimages/AppHighlight_BalancedPhotodetectors.pdf');
const delay = ref('ESO: VLTI delay-line subsystem', 'https://www.eso.org/sci/facilities/paranal/telescopes/vlti/subsystems/delaylines.html');
const fourier = ref('MIT: spatial filtering lecture', 'https://ocw.mit.edu/courses/2-71-optics-spring-2009/resources/mit2_71s09_lec18/');
const scan = ref('Thorlabs: scanning lenses', 'https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=2910');
const n = (id, label, x, y, note, type, params) => ({ id, label, x, y, note, ...(type ? { type } : {}), ...(params ? { params } : {}) });
const e = (from, to, label = '', kind = 'light', via) => ({ from, to, label, kind, ...(via ? { via } : {}) });
function record(id, title, summary, nodes, edges, steps, limit, references) {
  return { id, title, summary, nodes, edges, steps, limit, references: Array.isArray(references) ? references : [references], mode: 'schematic' };
}
function el(id, type, x, y, params = {}, rot = 0) {
  const element = createElement(type, x, y);
  return { ...element, id, rot, label: id, showLabel: true, params: { ...element.params, ...params } };
}
function live(record, elements) {
  return { ...record, mode: 'rays', scene: { version: 1, elements, beams: [] } };
}

export const examples = [
live(record('IMG-01', 'Unit-magnification 4f relay', 'Two 100 mm thin lenses relay an object plane to an inverted image over 400 mm; the shared focal plane remains accessible.', [
 n('object','Object plane',90,190,'Place a small target 100 mm before L1.'), n('l1','L1 · 100 mm',270,190,'First Fourier transform; object at its front focus.','lens',{f:100}), n('fourier','Fourier plane',450,190,'100 mm after L1 and before L2; a spatial-frequency plane.'), n('l2','L2 · 100 mm',630,190,'Reimages the first plane with magnification −1.','lens',{f:100}), n('image','Image plane',810,190,'100 mm after L2; object features are inverted.','camera'),
], [e('object','l1'),e('l1','fourier'),e('fourier','l2'),e('l2','image'),e('object','image','conjugate planes','reference',[[90,330],[810,330]])], ['Open the live scene: the separately drawn ideal image of the 10 mm F is inverted at −1 magnification; the traced fan comes from the on-axis object anchor.','Move the camera 30 mm beyond its image conjugate: the narrow fan broadens and the camera no longer lies at the ideal image plane.'], 'The fan traces on-axis geometrical rays, while the F marker is a separate paraxial image construction that does not model downstream clipping. No target-image irradiance, diffraction-limited transfer function or real-lens aberration is computed.', [conjugates,fourier]), [el('object','objarrow',80,200,{height:10,shape:'F',spread:8,nrays:7,wavelength:532,showImage:true}),el('first','lens',180,200,{f:100,dia:40}),el('second','lens',380,200,{f:100,dia:40}),el('image','camera',502,200,{ch:40})]),
live(record('IMG-02', 'Threefold Keplerian beam expander', 'A 50 mm lens and a 150 mm lens, separated by 200 mm, expand a collimated 3 mm beam to approximately 9 mm.', [
 n('laser','532 nm input',90,190,'A collimated beam with 3 mm diameter.','cwlaser'),n('l1','L1 · 50 mm',300,190,'Produces the intermediate real focus.','lens',{f:50}),n('focus','Real focus',480,190,'50 mm behind the first lens; keep high-power objects away.'),n('l2','L2 · 150 mm',660,190,'Recollimates after the shared focus.','lens',{f:150}),n('camera','Expanded beam',850,190,'Inspect increased beam width, not a magnified target.','camera'),
], [e('laser','l1'),e('l1','focus'),e('focus','l2'),e('l2','camera')], ['Open the ray example and compare beam width before and after the telescope.','Move L2 away from the 200 mm lens separation to see residual convergence or divergence.'], 'This live example uses paraxial thin lenses; diffraction, real-lens aberrations and damage at the focus are absent.', expanders), [el('input','cwlaser',80,200,{wavelength:532,beamWidth:3}),el('first','lens',250,200,{f:50,dia:25.4}),el('second','lens',450,200,{f:150,dia:25.4}),el('output','camera',650,200,{ch:30})]),
record('IMG-03','Twofold pupil relay','A 75/150 mm relay maps a 4 mm scanner pupil onto an 8 mm objective pupil without treating that plane as a sample image.',[
 n('scan','Scanner pupil',90,190,'A 4 mm steering aperture; this is the relayed plane.','galvo'),n('l1','75 mm relay',300,190,'Scanner sits one focal length before this lens.','lens',{f:75}),n('field','Intermediate field',490,190,'Shared focal plane; not the relayed pupil.'),n('l2','150 mm relay',680,190,'225 mm from L1 gives 2× pupil magnification.','lens',{f:150}),n('pupil','Objective pupil',870,190,'8 mm pupil, 150 mm after L2.','objective')
],[e('scan','l1'),e('l1','field'),e('field','l2'),e('l2','pupil'),e('scan','pupil','pupil conjugates','reference',[[90,330],[870,330]])],['Compare the pupil conjugacy annotation with the intermediate field plane.','Double the first pupil diameter and check whether the objective pupil would clip it.'],'Pupil placement is schematic; no high-NA objective aberration or pupil irradiance is computed.',conjugates),
record('IMG-04','Infinity microscope with filter space','A nominal 10× objective with 20 mm effective focal length and a 200 mm tube lens leaves a collimated region for a 550 nm filter.',[
 n('sample','Specimen',90,190,'Place specimen at objective front focal plane.','sample'),n('obj','10× objective',270,190,'Nominal f = 20 mm with a 200 mm tube lens.','objective'),n('filter','550 nm filter',450,190,'Inserted in infinity space, away from an image conjugate.','filter'),n('tube','200 mm tube lens',630,190,'Forms the intermediate image.','lens',{f:200}),n('image','Camera image',820,190,'Nominal magnification is −200/20 = −10.','camera')
],[e('sample','obj'),e('obj','filter','infinity space'),e('filter','tube'),e('tube','image')],['Identify where a filter can be inserted without deliberately moving the image plane.','Change tube-lens focal length and calculate the resulting nominal magnification.'],'The nominal microscope geometry is diagrammed; manufacturer-specific objective corrections and high-NA image quality are not represented.',conjugates),
record('IMG-05','Object-space telecentric inspection','A 100 mm imaging lens with the aperture stop at its rear focal plane inspects a nominally flat 20 mm part.',[
 n('part','20 mm part',90,190,'Part moves axially during inspection; chief rays should remain parallel in object space.'),n('lens','100 mm imaging lens',300,190,'Ideal positive lens; stop belongs behind it.','lens',{f:100}),n('stop','Rear-focal stop',510,190,'Located 100 mm behind lens to make object-space chief rays parallel.'),n('sensor','Image sensor',750,190,'Position chosen for the finite object conjugate.','camera'),n('motion','Axial part motion',90,330,'Compare apparent size over a small defocus range.')
],[e('part','lens'),e('lens','stop'),e('stop','sensor'),e('motion','part','height variation','reference')],['Find the stop relative to the rear focal plane.','Separate the nominal constancy of magnification from loss of focus when the part moves.'],'Telecentricity does not guarantee sharpness over unlimited depth; the schematic calculates neither depth of field nor lens distortion.',telecentric),
record('IMG-06','Folded two-mirror image relay','A pair of concave mirrors carries a UV image through a folded relay, leaving a real intermediate focus available for a field stop.',[
 n('object','UV object',90,90,'A 266 nm emitting plane.'),n('m1','Concave M1',310,90,'First curved reflector creates an intermediate image.','cmirror'),n('focus','Intermediate image',510,220,'Place a field stop here to limit field extent.'),n('m2','Concave M2',710,220,'Second reflector relays the image toward the detector.','cmirror'),n('image','UV image',870,90,'Coated detector observes final conjugate.','camera')
],[e('object','m1'),e('m1','focus'),e('focus','m2'),e('m2','image')],['Trace the folded image path and locate the accessible field stop.','Compare the absence of bulk-glass dispersion with the remaining alignment and off-axis aberration issues.'],'Mirror radii and off-axis prescription require optical design; this topology does not claim an aberration-corrected UV instrument.',ref('NASA: reflective optics for ultraviolet imaging','https://science.nasa.gov/mission/hubble/observatory/design/optics/')),
record('IMG-07','Tilted-plane inspection camera','A 30° tilted specimen is observed through a tilted lens and sensor arranged so their plane extensions meet along a common line.',[
 n('object','Tilted specimen',100,190,'Object plane tilted 30° relative to the nominal sensor plane.'),n('lens','Tiltable lens',350,190,'Lens plane extension must share the Scheimpflug intersection.','lens'),n('sensor','Tilted sensor',650,190,'Tilt independently from focusing translation.','camera'),n('intersection','Common intersection',350,330,'Plane extensions meet here; this is a geometrical constraint.')
],[e('object','lens'),e('lens','sensor'),e('object','intersection','object extension','reference'),e('lens','intersection','lens extension','reference'),e('sensor','intersection','sensor extension','reference')],['Follow all three plane-extension lines to the common intersection.','Treat sensor tilt and longitudinal focus as separate adjustments.'],'The plane intersection is schematic and does not solve lens tilt, projective distortion, depth of field or off-axis aberrations.',telecentric),
record('IMG-08','K-mirror field derotator','Three plane mirrors on one rotating mount derotate an astronomical field; a 15° mechanical rotation corresponds to a nominal 30° image rotation.',[
 n('field','Rotating sky field',90,90,'A field whose orientation changes while tracking.'),n('m1','First fold',300,90,'First reflector on the shared rotary mount.','mirror'),n('m2','Central mirror',480,240,'Second reflection defines the folded K path.','mirror'),n('m3','Third fold',670,90,'Third reflection returns toward the output direction.','mirror'),n('camera','Derotated camera',870,90,'Orientation is controlled by rotating the assembly.','camera'),n('mount','15° mount rotation',480,350,'All three mirrors rotate together.')
],[e('field','m1'),e('m1','m2'),e('m2','m3'),e('m3','camera'),e('mount','m1','shared mount','signal'),e('mount','m3','shared mount','signal')],['Follow the three reflections rather than interpreting the folded path as an image rotation simulation.','Compare the nominal twice-angle image rotation with the mount angle.'],'Image parity and 3D field rotation require a coordinate convention; the 2D diagram cannot calculate a derotated image.',ref('ESO: SPHERE instrument description and derotator','https://www.eso.org/sci/facilities/paranal/instruments/sphere/inst.html')),
record('IMG-09','Two-group compensated zoom','A movable variator changes nominal magnification from 1× to 2× while a separate compensator keeps the final image plane fixed.',[
 n('object','Fixed object',90,190,'Keep the object position fixed throughout zoom.'),n('fixed','Fixed front group',280,190,'Collects the object field.','lens'),n('var','Variator',470,190,'Moves to change the system focal length.','lens'),n('comp','Compensator',660,190,'Moves on a different trajectory to restore focus.','lens'),n('sensor','Fixed image plane',860,190,'Sensor position is not the compensating actuator.','camera'),n('cam','Coupled motion law',560,330,'Two trajectories must be solved together.')
],[e('object','fixed'),e('fixed','var'),e('var','comp'),e('comp','sensor'),e('cam','var','zoom motion','signal'),e('cam','comp','focus correction','signal')],['Identify the two independent moving groups.','Compare a 1× and 2× endpoint only after checking that both share the fixed sensor plane.'],'No prescription or cam law is solved here; arbitrary group translations do not constitute a working compensated zoom.',ref('Canon: zoom variator and compensator white paper','https://downloads.canon.com/bctv/4K_Box_Lenses_White_Paper.pdf')),
record('BEAM-01','Pinhole spatial filter','A 532 nm beam is focused by a 20 mm lens through a 10 µm pinhole and recollimated by a 100 mm lens.',[
 n('source','532 nm laser',90,190,'A nominal 2 mm collimated input.','cwlaser'),n('focus','20 mm focus lens',280,190,'Focuses near the pinhole.','lens',{f:20}),n('hole','10 µm pinhole',470,190,'Rejects off-axis spatial content at the focus.'),n('coll','100 mm collimator',660,190,'Output beam is nominally expanded fivefold.','lens',{f:100}),n('out','Clean output',860,190,'Inspect throughput and alignment trade-offs.')
],[e('source','focus'),e('focus','hole'),e('hole','coll'),e('coll','out')],['Locate the pinhole at the shared focal plane.','Compare pinhole size to the diffraction spot before expecting transmission.'],'A pinhole can geometrically clip rays in the editor, but this schematic does not calculate spatial-frequency rejection or an Airy pattern.',ref('Newport: spatial filters','https://www.newport.com/n/spatial-filters')),
record('BEAM-02','Fiber spatial-mode filter','A 780 nm beam is coupled into a single-mode fiber with nominal 5 µm mode-field diameter, then recollimated for downstream use.',[
 n('input','780 nm input',90,190,'Input may contain unwanted transverse modes.','cwlaser'),n('couple','Input asphere',300,190,'Match waist and wavefront to the fiber mode.','lens'),n('fiber','Single-mode fiber',510,190,'Nominal MFD 5 µm; actual cutoff must suit 780 nm.'),n('coll','Output collimator',720,190,'Sets output beam diameter.','lens'),n('loss','Rejected light',300,330,'Uncoupled power does not join the guided output.','beamdump')
],[e('input','couple'),e('couple','fiber','matched mode'),e('fiber','coll'),e('couple','loss','coupling loss')],['Distinguish cleaning the output mode from preserving all input power.','Check the fiber operating wavelength and match the input waist to the stated mode field.'],'The schematic does not compute a field-overlap integral; the editor fiber model is not proof of single-mode purity.',ref('Thorlabs: single-mode fiber coupling','https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=1421')),
record('BEAM-03','Two-lens cavity mode matching','A 50/100 mm adjustable lens pair targets a 100 µm waist at a cavity input mirror; matching size alone does not match curvature.',[
 n('laser','1064 nm input',90,190,'Nominal 1 mm beam radius.','cwlaser'),n('l1','50 mm lens',280,190,'First degree of freedom changes convergence.','lens',{f:50}),n('l2','100 mm lens',470,190,'Position provides a second waist-control degree of freedom.','lens',{f:100}),n('waist','100 µm target waist',660,190,'Desired waist belongs to the cavity eigenmode.'),n('cavity','Cavity input',850,190,'Mode overlap determines usable injection.','cmirror'),n('target','Target q parameter',660,330,'Both spot size and wavefront curvature must agree.')
],[e('laser','l1'),e('l1','l2'),e('l2','waist'),e('waist','cavity'),e('target','waist','mode constraint','reference')],['Use the two movable lenses to control waist position and size independently.','Compare both waist radius and wavefront curvature against the target eigenmode.'],'No Gaussian q propagation or cavity overlap is computed; the dimensions describe a design target, not a solved lens spacing.',ref('Newport: cavity mode matching appendix','https://www.newport.com/medias/sys_master/images/images/h73/he8/8797035429918/9091-User-Manual-RevD.pdf')),
record('BEAM-04','Cylindrical 4× anamorphic expander','A 25/100 mm cylindrical telescope expands one axis of a 2 × 8 mm diode beam to a nominal 8 × 8 mm beam.',[
 n('diode','2 × 8 mm beam',90,190,'Choose the narrow axis for expansion.','cwlaser'),n('c1','25 mm cylinder',300,190,'Power only in the narrow axis.'),n('c2','100 mm cylinder',530,190,'125 mm lens separation; parallel cylinder axes.'),n('profile','8 × 8 mm target',760,190,'Other transverse axis is nominally unchanged.'),n('axis','Unpowered axis',530,330,'No focal power along the cylinder axis.')
],[e('diode','c1'),e('c1','c2'),e('c2','profile'),e('axis','c2','axis convention','reference')],['Check that both cylinders expand the same transverse axis.','Compare the 4× narrow-axis expansion with the unchanged long axis.'],'Two transverse axes cannot be represented simultaneously by this 2D topology; astigmatism and diode divergence require a real beam prescription.',expanders),
record('BEAM-05','Gaussian-to-top-hat refractive mapper','Two aspheric surfaces redistribute a nominal 3 mm radius Gaussian input into a 4 mm radius flat-top output without deliberately clipping the center.',[
 n('gauss','Gaussian input',100,190,'Design input intensity and radius are part of the prescription.','cwlaser'),n('s1','Remapping surface',340,190,'Redirects annuli according to cumulative input power.','asphericlens'),n('s2','Recollimating surface',580,190,'Restores a planar output wavefront.','asphericlens'),n('flat','4 mm top-hat',820,190,'Target profile at the specified output plane.'),n('map','Cumulative power map',460,330,'Equal power within corresponding input/output radii.')
],[e('gauss','s1'),e('s1','s2'),e('s2','flat'),e('map','s1','surface prescription','reference'),e('map','s2','wavefront constraint','reference')],['Compare redistribution with lossy aperture truncation.','Change the assumed input radius and identify why a fixed remapper will no longer produce its design profile.'],'Generic asphere icons do not supply a solved remapping prescription; no top-hat irradiance is simulated.',ref('Newport: refractive beam shaping','https://www.newport.com/medias/sys_master/images/images/h0f/hab/8797246685214/Refractive-Beam-Shaper-Application-Note.pdf')),
record('BEAM-06','Fly-eye homogenizer','Two 300 µm-pitch microlens arrays and a 100 mm field lens overlap beamlets at a 5 mm target field.',[
 n('input','Uneven input',90,190,'Nominal 6 mm illumination beam.','cwlaser'),n('a1','First lenslet array',290,190,'Partitions the aperture into beamlets.'),n('a2','Second lenslet array',490,190,'Relays each beamlet toward a common field lens.'),n('field','100 mm field lens',690,190,'Superposes many lenslet images.','lens',{f:100}),n('target','5 mm target field',870,190,'Beamlet overlap reduces sensitivity to input structure.'),n('beamlet','Representative beamlet',490,330,'One channel among many; not an extra source.')
],[e('input','a1'),e('a1','a2','many parallel beamlets'),e('a2','field'),e('field','target'),e('a1','beamlet'),e('beamlet','a2','one of the relayed beamlets')],['Trace both a representative beamlet and the combined target field.','Distinguish averaging irradiance from eliminating coherent speckle.'],'Microlens arrays, overlap uniformity and coherent speckle are not traced; the target size is a design choice.',ref('Edmund Optics: microlens arrays','https://www.edmundoptics.com/f/microlens-arrays/13812/')),
record('BEAM-07','4f low-pass spatial filter','A circular stop at the common Fourier plane of a 100/100 mm relay suppresses high spatial frequencies of a test image.',[
 n('target','Line-pair target',90,190,'Object plane contains fine and coarse features.'),n('l1','100 mm lens',280,190,'Converts object structure to a Fourier-plane distribution.','lens',{f:100}),n('mask','Fourier-plane stop',470,190,'Central 1 mm radius aperture passes low spatial frequencies.'),n('l2','100 mm lens',660,190,'Transforms the filtered field back into an image.','lens',{f:100}),n('image','Filtered image',860,190,'Fine edges soften as the aperture contracts.','camera')
],[e('target','l1'),e('l1','mask','spatial spectrum'),e('mask','l2'),e('l2','image')],['Locate the filter between the two lenses, rather than in an image plane.','Compare low-pass central aperture selection with a central-blocking high-pass mask.'],'The topology does not compute a Fourier transform or a filtered image; a traced iris alone cannot demonstrate spatial-frequency filtering.',fourier),
record('BEAM-08','SLM hologram with order selection','A phase SLM at 532 nm encodes two equal target spots; a blazed carrier separates the selected order from undiffracted light.',[
 n('laser','532 nm expanded beam',90,190,'Polarization and aperture must suit the SLM.','cwlaser'),n('slm','Phase hologram',300,190,'Adds a carrier and a two-spot phase pattern.','slm'),n('fourier','Order-selection plane',510,190,'Stop selects the intended diffraction order.'),n('spot1','Target spot A',750,90,'One of two equal nominal target powers.'),n('spot2','Target spot B',750,290,'Second programmed target.'),n('zero','Zero-order dump',510,330,'Unmodulated light is rejected.','beamdump')
],[e('laser','slm'),e('slm','fourier'),e('fourier','spot1'),e('fourier','spot2'),e('slm','zero','undiffracted order')],['Follow the unwanted zero order separately from the two selected spots.','Compare the specified equal spot powers with the need to measure real diffraction efficiency.'],'The editor SLM supports a directional proxy; this schematic does not synthesize holograms or predict target spot intensity.',ref('Hamamatsu: wavefront modulation research','https://www.hamamatsu.com/us/en/our-company/business-domain/central-research-laboratory/optical-information-processing-and-measurement/wave.html')),
record('ILL-01','Köhler transmitted-light microscope','A lamp filament is conjugate to the condenser aperture while the field diaphragm is conjugate to the specimen.',[
 n('pointsource','Lamp filament',90,90,'Extended source, intentionally not focused on the specimen.','pointsource'),n('collector','Collector',280,90,'Images the filament into the aperture plane.','lens'),n('aperture','Aperture diaphragm',480,90,'Sets angular illumination extent.'),n('condenser','Condenser',680,190,'Forms the field-diaphragm image at the specimen.','lens'),n('sample','Specimen field',870,190,'Field and angular controls are independent.','sample'),n('field','Field diaphragm',280,290,'Limits illuminated area; focus its rim at the specimen.')
],[e('pointsource','collector'),e('collector','aperture'),e('aperture','condenser'),e('condenser','sample'),e('field','condenser'),e('field','sample','field conjugates','reference',[[280,350],[870,350]])],['Follow source/aperture and field/specimen conjugate sets independently.','Close the field diaphragm to the observed field and adjust aperture for illumination angle.'],'This diagram does not calculate extended-source uniformity or microscope resolution; aperture and field conjugacy are conceptual.',conjugates),
record('ILL-02','Critical LED illumination','A 1 mm LED die is directly imaged onto a 2 mm specimen field with a nominal 2× condenser relay.',[
 n('pointsource','1 mm LED die',100,190,'Die texture is part of the imaged source.','pointsource'),n('cond','Condenser relay',340,190,'Nominal 2× image magnification.','lens'),n('sample','2 mm specimen field',590,190,'Source nonuniformity can appear here.','sample'),n('camera','Inspection camera',830,190,'Inspect imprint of the die structure.','camera'),n('die','Die texture',100,330,'Contrast this source image with Köhler illumination.')
],[e('pointsource','cond'),e('cond','sample','source image'),e('sample','camera'),e('die','sample','imprinted structure','reference')],['Locate the source image at the specimen.','Compare a structured LED die with a smooth emitting surface and identify the expected illumination texture.'],'No extended LED image or uniformity metric is computed; the condenser is an illustrative relay rather than a solved source imaging lens.',ref('Nikon: critical illumination','https://www.microscopyu.com/glossary/critical-illumination')),
record('ILL-03','488 nm epi-fluorescence microscope','A 500 nm longpass dichroic reflects 488 nm excitation into a shared objective and transmits nominal 520 nm fluorescence toward the camera.',[
 n('laser','488 nm excitation',100,90,'Clean the excitation spectrum before injection.','cwlaser'),n('dich','500 nm dichroic',350,190,'Reflect short wavelengths, transmit long wavelengths.','dichroic',{cutoff:500}),n('obj','Shared objective',570,190,'Excitation and collection use the same objective.','objective'),n('sample','Fluorescent specimen',800,190,'Chosen emission near 520 nm.','sample'),n('filter','520 nm emission filter',350,330,'Reject residual excitation before detection.','filter'),n('camera','Emission camera',100,330,'Read the emission branch.','camera')
],[e('laser','dich','488 nm'),e('dich','obj','excitation'),e('obj','sample'),e('sample','obj','520 nm return'),e('obj','dich','collection'),e('dich','filter','520 nm'),e('filter','camera')],['Follow excitation and emission through the shared objective in opposite directions.','Identify the additional emission filter rather than relying only on the dichroic cutoff.'],'Fluorescence spectrum, collection solid angle and filter leakage are not calculated by this schematic.',ref('Nikon: fluorescence filter combinations','https://www.microscopyu.com/techniques/fluorescence/fluorescence-filter-combinations')),
record('ILL-04','Annular pupil illumination','An annulus occupying normalized pupil radii 0.6–0.8 illuminates a specimen with a selected cone of angles.',[
 n('source','Extended source',90,190,'Supply a broad illumination pupil.','pointsource'),n('annulus','0.6–0.8 pupil annulus',330,190,'Shape angular content at an aperture conjugate.'),n('relay','Pupil relay',570,190,'Relays the annulus to the condenser pupil.','lens'),n('sample','Specimen',820,190,'Receives oblique illumination directions.','sample'),n('pupil','Condenser pupil',570,330,'Annulus must be centered in this conjugate.')
],[e('source','annulus'),e('annulus','relay'),e('relay','sample','angular cone'),e('annulus','pupil','pupil conjugates','reference'),e('pupil','sample','illumination angles','reference')],['Confirm that the annulus belongs to a pupil plane rather than a specimen image plane.','Compare centering errors with changing inner and outer annular radii.'],'Normalized pupil radii specify a target distribution; no vector illumination field or annular diffraction is calculated.',conjugates),
record('ILL-05','Three-phase stripe projection','A DMD projects 10 µm-period stripes onto a sample with phases 0°, 120° and 240° for separate camera acquisitions.',[
 n('source','Green illumination',90,190,'Choose 532 nm for this concrete pattern projection.','cwlaser'),n('dmd','Three stripe patterns',310,190,'Sequential phases, not simultaneous frames.','dmd'),n('relay','Projection relay',530,190,'Sets a 10 µm period at the specimen.','lens'),n('sample','Patterned specimen',750,190,'Pattern moves across the same field.','sample'),n('camera','Three camera frames',750,330,'Collect one frame per phase.','camera'),n('sequence','0° / 120° / 240°',310,330,'Synchronize pattern changes and exposures.')
],[e('source','dmd'),e('dmd','relay'),e('relay','sample'),e('sample','camera'),e('sequence','dmd','pattern control','signal'),e('sequence','camera','exposure trigger','signal')],['Follow the exposure synchronization as well as the optical path.','Compare projected period at the sample with the pattern period on the modulator.'],'No patterned image, reconstruction or super-resolution claim is simulated; three phases alone are not a complete SIM acquisition.',ref('Gustafsson: structured illumination beyond the classical resolution limit','https://doi.org/10.1046/j.1365-2818.2000.00710.x')),
record('ILL-06','Orthogonal light-sheet microscope','A cylindrical lens forms a thin illumination sheet through the specimen; a separate objective collects fluorescence at 90°.',[
 n('laser','488 nm beam',90,190,'Nominal 2 mm beam before the cylindrical optics.','cwlaser'),n('cyl','Sheet-forming cylinder',310,190,'Focus one axis and leave the other extended.'),n('sample','Illuminated slice',550,190,'Sheet lies in the detection focal plane.','sample'),n('obj','Detection objective',550,330,'Collects orthogonal to illumination.','objective'),n('camera','Slice camera',790,330,'Image plane captures one optical section.','camera'),n('scan','Specimen translation',790,90,'Step through a volume with separate acquisitions.')
],[e('laser','cyl'),e('cyl','sample','light sheet'),e('sample','obj','orthogonal collection'),e('obj','camera'),e('scan','sample','volume stepping','signal')],['Follow orthogonal illumination and detection axes.','Compare changing sheet thickness with stepping the specimen through the fixed detection plane.'],'Sheet waist, Rayleigh range and fluorescence volume are not computed; the transverse sheet extent is outside the 2D editor.',ref('Huisken et al.: selective plane illumination microscopy','https://doi.org/10.1126/science.1100035')),
record('ILL-07','Fourfold reduction exposure','A 40 mm mask field is reduced to a 10 mm substrate field by a nominal −0.25× projection relay.',[
 n('illum','365 nm illuminator',90,190,'Illuminate the mask field uniformly.'),n('mask','40 mm mask field',280,190,'Object plane defines pattern geometry.'),n('projection','−0.25× projection',500,190,'A 200/50 mm relay is one paraxial realization.','lens'),n('wafer','10 mm substrate field',740,190,'Image plane receives the reduced pattern.','sample'),n('pupil','Illumination pupil',500,330,'Controls angular spectrum independently of mask features.')
],[e('illum','mask'),e('mask','projection'),e('projection','wafer'),e('pupil','projection','pupil shaping','reference')],['Compare mask and substrate feature scales using the 4:1 reduction.','Keep the substrate at the image conjugate and separate illumination-pupil tuning from magnification.'],'No resist exposure, process window, high-NA projection prescription or lithographic resolution is predicted.',ref('ASML: TWINSCAN NXT:1965Ci reduction projection system','https://www.asml.com/en/products/duv-lithography-systems/twinscan-nxt-1965ci')),
record('ILL-08','Four-spot microlens illuminator','A 2 × 2 lenslet array creates four simultaneous focal spots; total incident power must be shared across the four channels.',[
 n('input','532 nm input',90,190,'Illuminate all four lenslets with equal nominal irradiance.','cwlaser'),n('array','2 × 2 lenslets',320,190,'Four physical subapertures partition the beam.'),n('a','Spot A / B',580,90,'Upper row of two target spots.'),n('b','Spot C / D',580,290,'Lower row of two target spots.'),n('sample','Four-site specimen',820,190,'All four sites are illuminated simultaneously.','sample')
],[e('input','array'),e('array','a','two upper channels'),e('array','b','two lower channels'),e('a','sample'),e('b','sample')],['Count four channels even though the diagram groups them in two rows.','Compare total laser power with per-spot power and the effect of unequal lenslet illumination.'],'Lenslet diffraction, spot spacing and equalization are not calculated; the topology is distinct from a programmable SLM hologram.',ref('Edmund Optics: microlens arrays','https://www.edmundoptics.com/f/microlens-arrays/13812/')),
record('SCAN-01','Single-axis pupil-conjugate scanner','A galvo is relayed at 1× to an objective pupil so steering changes the focused spot position with minimal pupil walk.',[
 n('input','Collimated input',90,190,'Keep the beam smaller than the galvo clear aperture.','cwlaser'),n('galvo','Galvo pivot',280,190,'The reflecting pivot is the relayed pupil plane.','galvo'),n('relay','100/100 mm relay',490,190,'Two-lens 4f conjugation of the pivot.','lens'),n('pupil','Objective pupil',700,190,'Relayed galvo plane coincides with entrance pupil.','objective'),n('target','Scanned focal plane',870,190,'Objective converts steering angle to spot displacement.','sample')
],[e('input','galvo'),e('galvo','relay'),e('relay','pupil'),e('pupil','target'),e('galvo','pupil','pupil conjugates','reference',[[280,330],[700,330]])],['Distinguish movement of the focused spot from lateral pupil walk.','Check the conjugation of the galvo pivot before increasing scan angle.'],'Scanner conjugacy is schematic; no high-NA scan field, clipping curve or telecentricity calibration is predicted.',[conjugates,scan]),
record('SCAN-02','Relayed X and Y galvos','A 75/75 mm 4f relay images the X-galvo pivot onto the Y-galvo pivot before a second relay to the objective pupil.',[
 n('x','X galvo',90,190,'First scan axis, at the first conjugate pivot.','galvo'),n('relay','75/75 mm relay',310,190,'150 mm lens separation preserves the pivot plane.','lens'),n('y','Y galvo',530,190,'Second axis shares a conjugate pupil with the first.','galvo'),n('objrelay','Objective pupil relay',750,190,'Relays both angular controls to the final pupil.','lens'),n('target','Two-axis scan field',750,330,'Objective follows the relay; X and Y are independent coordinates.')
],[e('x','relay'),e('relay','y'),e('y','objrelay'),e('objrelay','target'),e('x','y','pivot conjugates','reference',[[90,330],[530,330]])],['Compare relayed galvos with two nearby but nonconjugate mirrors.','Check that both pivots map to the objective pupil before discussing a 2D raster.'],'Orthogonal scan axes are shown topologically; the 2D ray editor cannot represent the full two-axis raster simultaneously.',conjugates),
record('SCAN-03','Confocal scan and descan return','The same galvo scans excitation and descans the reciprocal return before a stationary 50 µm detection pinhole.',[
 n('laser','Excitation',90,90,'A fixed incident beam.','cwlaser'),n('split','Return separator',320,190,'Directs the returning signal to detection.','dichroic'),n('galvo','Shared galvo',550,190,'Outbound and return paths use the same pivot.','galvo'),n('sample','Scanned specimen',800,190,'Objective images the scanned focal point.','sample'),n('hole','50 µm fixed pinhole',320,330,'Return image remains stationary after descan.'),n('det','Confocal detector',90,330,'Collect only the pinhole-transmitted return.','detector')
],[e('laser','split'),e('split','galvo'),e('galvo','sample','scan'),e('sample','galvo','return'),e('galvo','split','descan'),e('split','hole'),e('hole','det')],['Trace the common outbound/return galvo and the stationary detector branch.','Compare scanner misconjugation with a pinhole simply being off-center.'],'No confocal point-spread function, return-image descan or pinhole sectioning is calculated by this diagram.',ref('Nikon: confocal scanning optical systems','https://www.microscopyu.com/techniques/confocal/confocal-microscope-scanning-systems')),
record('SCAN-04','100 mm f-theta processing head','A nominal 100 mm f-theta lens maps ±5° optical scan angles to approximately ±8.73 mm of target displacement.',[
 n('beam','Expanded process beam',90,190,'Fill the specified scanning-lens pupil.','cwlaser'),n('galvo','±5° optical scan',320,190,'Optical deflection is twice the mirror angle.','galvo'),n('lens','100 mm f-theta lens',560,190,'Design target is x = fθ, with θ in radians.','lens'),n('field','±8.73 mm target',800,190,'Flat processing field, nominally linear in angle.','sample'),n('control','Angle command',320,330,'Calibrate angle-to-position against the real lens.')
],[e('beam','galvo'),e('galvo','lens'),e('lens','field'),e('control','galvo','scan command','signal')],['Calculate 100 × 5π/180 mm and distinguish optical angle from mechanical galvo angle.','Compare ideal fθ placement with measured field distortion and focus variation.'],'The thin-lens icon is not an f-theta prescription; no flat-field correction, process dose or calibrated scan is simulated.',scan),
record('SCAN-05','Remote mirror focus translation','A pupil-matched objective pair images an axially translating remote mirror into the specimen space while the specimen objective stays fixed.',[
 n('input','Imaging beam',90,190,'Beam enters the remote-focusing train.'),n('remote','Remote objective',300,190,'Forms a focus near the translating mirror.','objective'),n('mirror','Axial remote mirror',520,190,'Translate ±20 µm around the conjugate focus.','mirror'),n('relay','Pupil-matched relay',520,330,'Return travels to the specimen objective through matched pupils.','lens'),n('sampleobj','Specimen objective',740,330,'Remains stationary.','objective'),n('sample','Shifted specimen focus',870,190,'Remote axial displacement maps into specimen space.','sample')
],[e('input','remote'),e('remote','mirror'),e('mirror','remote','return'),e('remote','relay','refocused beam'),e('relay','sampleobj'),e('sampleobj','sample')],['Follow the round trip through the remote objective.','Separate moving the remote mirror from physically moving the specimen objective.'],'Axial magnification and aberration cancellation depend on pupil and refractive-index matching; the ±20 µm motion is illustrative.',ref('Botcherby et al.: aberration-free optical refocusing','https://doi.org/10.1016/j.optcom.2007.10.007')),
record('SCAN-06','Moving-retroreflector delay stage','A retroreflector translates 15 mm on a carriage, changing the free-space round-trip path by 30 mm, approximately 100 ps, with a fixed output axis.',[
 n('input','Fixed input beam',90,90,'Input stays aligned during carriage travel.','pulsedlaser'),n('fold','Input/output fold',320,90,'Separates parallel in/out paths.','mirror'),n('retroreflector','Moving retroreflector',650,90,'Carriage stroke is 15 mm.','retroreflector'),n('out','Fixed output',320,290,'Returned beam remains on the output axis.'),n('stage','15 mm translation',650,290,'Round trip gives twice the carriage displacement.','stage')
],[e('input','fold'),e('fold','retroreflector'),e('retroreflector','out','30 mm extra path', 'light',[[800,190],[650,290]]),e('stage','retroreflector','carriage motion','signal')],['Use Δt = 2Δx/c to convert 15 mm carriage travel to roughly 100 ps.','Check fixed output pointing independently of path-length change.'],'Topology and free-space timing relation are shown; stage tolerances, air-index dispersion and beam walk are not simulated.',delay),
record('SCAN-07','80 MHz double-pass AOM','A cat-eye return traverses an 80 MHz AOM twice; polarization separation extracts a nominal +160 MHz output while suppressing pointing sensitivity.',[
 n('input','Input laser',90,90,'Input linear polarization passes the PBS.','cwlaser'),n('pbs','Polarization separator',300,90,'Send and return occupy different polarization ports.','pbs'),n('aom','80 MHz AOM',530,90,'Selected diffraction order is traversed twice.','aom'),n('cat','Cat-eye lens',750,90,'Focus the selected order onto the end reflector.','lens'),n('mirror','Quarter-wave / mirror',750,290,'Double-pass polarization rotates the return by 90°.','mirror'),n('out','+160 MHz return',300,290,'Extracted PBS return port.')
],[e('input','pbs'),e('pbs','aom'),e('aom','cat','first +80 MHz'),e('cat','mirror'),e('mirror','cat','return'),e('cat','aom','second +80 MHz'),e('aom','pbs'),e('pbs','out')],['Count two frequency shifts in the selected order.','Follow the cat-eye return and identify why the extracted output uses the other PBS port.'],'The diagram does not calculate RF frequency shifts, cat-eye alignment or frequency-dependent output pointing; the quarter-wave element is described at the end mirror.',ref('Donley et al., NIST: compact double-pass AOM','https://www.nist.gov/publications/compact-double-pass-acousto-optic-modulator-system')),
record('SCAN-08','Herriott-cell multipass absorption','Two concave mirrors repeatedly pass a beam through a 200 mm gas cell before the selected exit aperture reaches a detector.',[
 n('input','Probe input',90,190,'Choose a near-infrared absorption wavelength.','cwlaser'),n('m1','Input/exit mirror',310,190,'Entrance and exit holes select a finite spot sequence.','cmirror'),n('gas','200 mm gas region',540,190,'Repeated traversals increase absorption path.','gascell'),n('m2','Opposite mirror',770,190,'Concave mirror supports a stable multipass orbit.','cmirror'),n('det','Selected exit detector',310,330,'Only the selected exiting spot reaches detection.','detector')
],[e('input','m1'),e('m1','gas'),e('gas','m2'),e('m2','gas','next pass','light',[[770,90],[540,90]]),e('gas','m1','return pass','light',[[540,290]]),e('m1','det','exit aperture')],['Count physical traversals rather than multiplying by the number of mirror spots without checking the sequence.','Distinguish a finite multipass orbit with an exit hole from a resonant cavity.'],'Mirror separation and curvature alone do not specify the 3D Herriott orbit; no gas-line absorption spectrum or spot sequence is calculated.',ref('Herriott et al.: off-axis paths in spherical-mirror interferometers','https://doi.org/10.1364/AO.3.000523')),
live(record('ROUTE-01','Two-color dichroic splitter','Coaxial 488 and 640 nm beams encounter a 550 nm longpass dichroic: red transmits and blue reflects into a second detector.',[
 n('input','488 + 640 nm input',90,190,'Two wavelengths share one incident axis.','cwlaser'),n('dich','550 nm longpass',350,190,'At 45°, short wavelengths are reflected.','dichroic',{cutoff:550}),n('red','640 nm detector',650,190,'Transmitted long-wavelength channel.','detector'),n('blue','488 nm detector',350,330,'Reflected short-wavelength channel.','detector')
],[e('input','dich'),e('dich','red','640 nm'),e('dich','blue','488 nm')],['Open the traced scene and read the wavelength at each detector.','Move the cutoff below 488 nm or above 640 nm to send both colors to the same port.'],'The dichroic model uses ideal wavelength bands; angle-dependent coating spectra, transition width and leakage are absent.',ref('Edmund Optics: optical beamsplitter selection','https://www.edmundoptics.com/c/beamsplitters/622/')),[el('blue-input','cwlaser',70,200,{wavelength:488,beamMode:'line'}),el('red-input','cwlaser',70,200,{wavelength:640,beamMode:'line'}),el('dichroic','dichroic',350,200,{cutoff:550,length:40},-45),el('red-output','detector',600,200),el('blue-output','detector',350,400,{},90)]),
live(record('ROUTE-02','Equal-power polarization splitter','A 532 nm beam with linear polarization at 45° enters a PBS and divides into orthogonal polarization channels.',[
 n('input','45° linear input',90,190,'Equal components in the PBS basis.','cwlaser'),n('pbs','Polarizing splitter',350,190,'Projects the input onto two orthogonal linear states.','pbs'),n('p','Transmitted channel',650,190,'One linear basis state.','detector'),n('s','Reflected channel',350,330,'Orthogonal linear basis state.','detector')
],[e('input','pbs'),e('pbs','p'),e('pbs','s')],['Compare detector powers and polarization states in the traced example.','Set input polarization to 0° or 90° and verify extinction of the complementary port.'],'Ideal Stokes projection is traced; finite PBS extinction, coating phase and depolarization are absent.',ref('Edmund Optics: polarizing beamsplitters','https://www.edmundoptics.com/c/polarizing-beamsplitters/701/')),[el('input','cwlaser',80,200,{wavelength:532,pol:45,beamMode:'line'}),el('splitter','pbs',350,200,{},90),el('transmitted','detector',600,200),el('reflected','detector',350,400,{},90)]),
live(record('ROUTE-03','Half-wave power attenuator','A half-wave plate at 22.5° rotates a horizontal 532 nm input to 45°; a horizontal analyzer passes half the input power.',[
 n('input','Horizontal input',90,190,'Linear polarization at 0°.','cwlaser'),n('hwp','HWP · 22.5°',300,190,'Output polarization rotates by twice the fast-axis angle.','hwp',{a:22.5}),n('analyzer','0° analyzer',530,190,'Malus-law transmission is cos²(45°) = 0.5.','polarizer',{pangle:0}),n('det','Half-power output',770,190,'Read power after the analyzer.','detector'),n('loss','Rejected polarization',530,330,'Absorbed by the analyzer; not an extra transmitted beam.')
],[e('input','hwp'),e('hwp','analyzer'),e('analyzer','det'),e('analyzer','loss','rejected power','reference')],['Read half-power transmission at 22.5° in the live scene.','Rotate the HWP to 0° and 45° to compare full transmission and extinction.'],'Ideal retardance and Malus-law attenuation are traced; absorption heating and wavelength-dependent plate errors are absent.',plates),[el('input','cwlaser',80,200,{wavelength:532,pol:0,beamMode:'line'}),el('plate','hwp',250,200,{a:22.5}),el('analyzer','polarizer',400,200,{pangle:0}),el('output','detector',600,200)]),
record('ROUTE-04','Quarter-wave shared-aperture return','A PBS transmits horizontal input through a quarter-wave plate at 45°; reflection and the second pass produce a vertical return at the other port.',[
 n('input','Horizontal laser',90,90,'Linear polarization passes the send port.','cwlaser'),n('pbs','Send/return PBS',330,90,'Separate return by orthogonal polarization.','pbs'),n('qwp','QWP · 45°',570,90,'First pass converts linear to circular; second pass rotates linear state.','qwp',{a:45}),n('target','Reflecting target',810,90,'Return must preserve the required polarization transformation.','mirror'),n('receive','Return detector',330,290,'Collects the orthogonal PBS port.','detector')
],[e('input','pbs'),e('pbs','qwp'),e('qwp','target'),e('target','qwp','reflected return','light',[[810,230],[570,230]]),e('qwp','pbs','orthogonal linear return'),e('pbs','receive')],['Count two passes through the quarter-wave plate.','Compare a specular reflector with a depolarizing sample that leaks into both ports.'],'This schematic does not assert that a rough target maintains polarization; return efficiency and real extinction require measurement.',plates),
record('ROUTE-05','Faraday isolator for laser protection','A 45° Faraday rotator between 0° and 45° polarizers transmits forward light while the nonreciprocal return reaches the first polarizer at 90°.',[
 n('laser','Laser output',90,190,'Protect against light returning from downstream optics.','cwlaser'),n('p0','0° input polarizer',280,190,'Defines the forward input state.','polarizer'),n('faraday','45° Faraday rotation',470,190,'Rotation adds on the reverse pass rather than undoing itself.','isolator'),n('p45','45° output polarizer',660,190,'Aligned to the forward state.','polarizer'),n('load','Reflective load',850,190,'May send a reverse beam.'),n('reject','Return rejection',280,330,'Reverse state is crossed at the input polarizer.','beamdump')
],[e('laser','p0'),e('p0','faraday'),e('faraday','p45'),e('p45','load'),e('load','p45','reverse light','light',[[850,90],[660,90]]),e('p45','faraday','reverse polarization'),e('faraday','p0','90° return state'),e('p0','reject','crossed-state rejection')],['Compare same-sense Faraday rotation in both propagation directions.','Identify where reverse power is absorbed or dumped.'],'The editor isolator is a directional gate; this internal topology does not compute magneto-optic dispersion or certified isolation.',ref('Thorlabs: optical isolator tutorial','https://www.thorlabs.com/catalogPages/682.pdf')),
record('ROUTE-06','Dual-polarization coherent receiver','A PBS splits an unknown 1550 nm signal into H and V components; each receives its own coherent hybrid and balanced readout.',[
 n('signal','1550 nm signal',90,190,'Unknown polarization may vary in time.'),n('pbs','Polarization demux',310,190,'Keep both orthogonal components.','pbs'),n('h','H coherent hybrid',530,90,'Mix H signal with a matched local-oscillator component.'),n('v','V coherent hybrid',530,290,'Mix V signal with its own LO component.'),n('dh','H I/Q readout',800,90,'Calibrated quadratures for H channel.','detector'),n('dv','V I/Q readout',800,290,'Calibrated quadratures for V channel.','detector'),n('lo','Shared local oscillator',310,330,'Distribute coherent LO light to both hybrids.','cwlaser')
],[e('signal','pbs'),e('pbs','h','H'),e('pbs','v','V'),e('lo','h','LO H'),e('lo','v','LO V'),e('h','dh'),e('v','dv')],['Follow both polarization channels instead of discarding one PBS port.','Separate optical polarization diversity from downstream digital polarization tracking.'],'No hybrids, data modulation or polarization recovery are computed; schematic detection channels do not imply a functioning telecom receiver.',coherent),
record('ROUTE-07','Prepare circular light and analyze it','A 0° polarizer followed by a 45° quarter-wave plate prepares circular input; a second quarter-wave plate and rotating analyzer measure its state.',[
 n('source','532 nm source',90,190,'Input may have an imperfect polarization state.','cwlaser'),n('prep','0° preparation polarizer',280,190,'Defines horizontal linear polarization.','polarizer'),n('q1','45° preparation QWP',470,190,'Prepares nominal circular polarization.','qwp'),n('q2','Analysis QWP',660,190,'Convert elliptical components before linear analysis.','qwp'),n('analyzer','Rotating analyzer',850,190,'Acquire several orientations.','polarizer'),n('det','Power readings',850,330,'Intensity sequence supports calibrated Stokes estimation.','detector')
],[e('source','prep'),e('prep','q1'),e('q1','q2'),e('q2','analyzer'),e('analyzer','det')],['Distinguish preparation optics from the separate analysis optics.','Compare readings with and without the analysis quarter-wave plate; linear analysis alone cannot determine circular handedness.'],'The schematic does not perform a calibrated Stokes fit or determine experimental plate conventions; wavelength errors and uncertainty remain external.',plates),
live(record('ROUTE-08','90/10 sample and monitor split','A 532 nm beam sends 90% through a sample with 50% excitation transmission and 10% to an independent reference photodiode.',[
 n('input','532 nm input',90,190,'Common source-power fluctuations affect both branches.','cwlaser'),n('split','90/10 splitter',330,190,'90% transmission and 10% reflection.','bs',{ratio:0.9}),n('sample','50% sample',570,190,'Sample branch loses half its incident power.','sample'),n('signal','Sample detector',820,190,'Expected 45% of source power in this ideal model.','detector'),n('monitor','Reference diode',330,330,'Expected 10% of source power.','detector')
],[e('input','split'),e('split','sample','90%'),e('sample','signal'),e('split','monitor','10%')],['Compare sample/reference power ratio, nominally 4.5 for the chosen transmissions.','Change source power and verify that both readings scale while their ratio stays fixed.'],'The traced model shows relative branch power and linear transmission; shot noise, electronics and calibrated normalization are not included.',ref('Edmund Optics: beamsplitter operation','https://www.edmundoptics.eu/knowledge-center/application-notes/optics/what-are-beamsplitters')),[el('input','cwlaser',80,200,{wavelength:532,beamMode:'line'}),el('splitter','bs',300,200,{ratio:0.9},90),el('sample','sample',450,200,{transmitExc:true,transmission:0.5,channels:[]},90),el('signal','detector',650,200),el('reference','detector',300,400,{},90)]),
record('FIELD-01','Mach–Zehnder phase measurement','Two 50/50 beamsplitters form separate sample and reference arms at 532 nm, then recombine into two complementary camera ports.',[
 n('laser','532 nm laser',90,190,'Shared coherent source.','cwlaser'),n('bs1','50/50 input splitter',290,190,'Creates two arms.','bs'),n('sample','Sample arm',490,90,'A phase object changes optical path.','phaseplate'),n('ref','Reference arm',490,290,'Adjustable optical delay.','delayline'),n('bs2','Recombiner',690,190,'Spatial mode and polarization must overlap.','bs'),n('a','Camera port A',870,90,'One complementary output.','camera'),n('b','Camera port B',870,290,'Complementary output checks total power.','camera')
],[e('laser','bs1'),e('bs1','sample'),e('bs1','ref'),e('sample','bs2'),e('ref','bs2'),e('bs2','a'),e('bs2','b')],['Compare separate sample and reference paths and both recombination outputs.','A 266 nm optical-path change at 532 nm adds π phase; distinguish optical path from physical mirror travel.'],'The schematic does not calculate fringes; finite coherence, visibility and phase-sensitive camera behavior require a traced interferometer geometry.',ref('MIT: interferometers lecture','https://ocw.mit.edu/courses/2-71-optics-spring-2009/resources/mit2_71s09_lec15/')),
record('FIELD-02','Point-diffraction common-path reference','A focused field crosses a pinhole reference mask: a small spatially filtered component supplies the reference and the remaining field carries specimen phase.',[
 n('object','Phase specimen',90,190,'Specimen modifies the incident wavefront.','phaseplate'),n('focus','Fourier lens',320,190,'Forms a focus at the reference mask.','lens'),n('mask','Reference pinhole mask',550,190,'Small hole generates a smooth reference wave.'),n('camera','Interference camera',810,190,'Reference and object fields propagate together.','camera'),n('ref','Filtered reference',550,330,'Co-propagating reference is derived from the same field.')
],[e('object','focus'),e('focus','mask'),e('mask','camera','object field'),e('mask','ref','pinhole reference'),e('ref','camera','shared downstream path')],['Identify where the reference is generated from the measured field.','Compare common downstream disturbances with disturbances before the pinhole reference formation.'],'No pinhole diffraction or common-path phase reconstruction is computed; a single aperture ray model is insufficient.',ref('Smartt and Steel: theory and application of point-diffraction interferometers','https://doi.org/10.7567/JJAPS.14S1.351')),
record('FIELD-03','Triangular Sagnac loop','A 50/50 splitter launches clockwise and counterclockwise beams around the same three-mirror loop before recombination.',[
 n('laser','633 nm input',90,190,'One coherent input.','cwlaser'),n('bs','Loop splitter',310,190,'Launches two counterpropagating copies.','bs'),n('m1','Upper loop mirror',530,90,'Shared loop segment.','mirror'),n('m2','Far loop mirror',770,190,'Closes the triangular area.','mirror'),n('m3','Lower loop mirror',530,290,'Both directions encounter this mirror.','mirror'),n('det','Loop output',90,330,'Recombined counterpropagating fields.','camera')
],[e('laser','bs'),e('bs','m1','clockwise'),e('m1','m2'),e('m2','m3'),e('m3','bs'),e('bs','m3','counterclockwise'),e('m3','m2'),e('m2','m1'),e('m1','bs'),e('bs','det')],['Trace both directions around the same loop.','Distinguish reciprocal shared-path changes from nonreciprocal effects or rotation.'],'Loop area and rotation sensitivity are not computed; schematic arrows do not represent a gyro or phase-calibrated Sagnac interferometer.',ref('Migdall et al., NIST: fiber Sagnac experimental topology','https://physics.nist.gov/Divisions/Div844/publications/migdall/TomographyfiberentanglementOptExpress.pdf')),
record('FIELD-04','Lateral shear collimation test','A weakly wedged plate produces two reflected copies of a 10 mm beam with a nominal 1 mm lateral shear, compared on an observation screen.',[
 n('beam','10 mm test beam',100,190,'Beam whose collimation is unknown.','cwlaser'),n('plate','Wedged shear plate',350,190,'Front and rear reflections overlap with lateral offset.','window'),n('copy1','First wavefront copy',580,90,'Front-surface reflection.'),n('copy2','1 mm shifted copy',580,290,'Rear-surface reflection.'),n('screen','Overlap screen',820,190,'Fringe direction changes with wavefront curvature.','camera')
],[e('beam','plate'),e('plate','copy1'),e('plate','copy2'),e('copy1','screen'),e('copy2','screen')],['Compare the two overlapping copies with a separate external reference wave.','Keep overlap while adjusting a collimator; identify the shear direction before interpreting fringes.'],'The plate icon does not implement two-surface coherent shear; neither fringe angle nor wavefront gradient is calculated.',ref('Thorlabs: shearing interferometer catalogue and operation','https://www.thorlabs.com/images/Catalog/V21/V21_7_LightAnalysis.pdf')),
record('FIELD-05','Differential balanced photodetection','Two complementary optical outputs with nominal 0.5 mW each enter matched 0.8 A/W photodiodes; a difference amplifier suppresses their common term.',[
 n('a','Optical port A',90,90,'Nominal 0.5 mW complementary port.'),n('b','Optical port B',90,290,'Nominal 0.5 mW complementary port.'),n('da','Photodiode A',350,90,'Chosen responsivity 0.8 A/W.','detector'),n('db','Photodiode B',350,290,'Match responsivity, gain and delay to A.','detector'),n('diff','Difference amplifier',620,190,'Subtract photocurrents: iA − iB.'),n('out','Differential output',850,190,'Equal nominal inputs give zero DC difference.')
],[e('a','da'),e('b','db'),e('da','diff','iA','signal'),e('db','diff','−iB','signal'),e('diff','out','difference','signal')],['Calculate each nominal photocurrent as 0.4 mA.','Introduce a 1% responsivity mismatch and identify the residual common-mode term.'],'No amplifier bandwidth, common-mode rejection, shot noise or photocurrent subtraction is executed by the schematic.',coherent),
record('FIELD-06','10 MHz heterodyne receiver','A 1550 nm signal and a local oscillator offset by 10 MHz mix at a 50/50 coupler; balanced electronics isolate a 10 MHz beat.',[
 n('sig','1550 nm signal',90,90,'Weak measured optical field.'),n('lo','10 MHz-offset LO',90,290,'Coherent local oscillator with chosen frequency offset.','cwlaser'),n('mix','50/50 optical mixer',350,190,'Match spatial mode and polarization.','bs'),n('a','Complementary port A',580,90,'One optical mixer output.','detector'),n('b','Complementary port B',580,290,'Opposite beat phase.','detector'),n('rf','10 MHz balanced beat',830,190,'Electrical subtraction recovers the beat amplitude and phase.')
],[e('sig','mix'),e('lo','mix'),e('mix','a'),e('mix','b'),e('a','rf','photocurrent','signal'),e('b','rf','−photocurrent','signal')],['Follow the strong LO separately from the weak signal.','Compare zero-frequency homodyne reception with the selected 10 MHz heterodyne offset.'],'Frequency-offset beating and RF electronics are not represented by static rays; the two optical wavelengths are nominally indistinguishable on this scale.',coherent),
record('FIELD-07','90° optical hybrid I/Q readout','A coherent hybrid combines a signal and LO with phases 0°, 90°, 180° and 270°; two balanced pairs measure I and Q.',[
 n('sig','Complex signal',90,90,'Unknown signal phase relative to LO.'),n('lo','Local oscillator',90,290,'Defines the quadrature reference.','cwlaser'),n('hybrid','90° optical hybrid',330,190,'Four phase-related output ports.'),n('ip','0° / 180° pair',560,90,'Complementary real-quadrature outputs.','detector'),n('qp','90° / 270° pair',560,290,'Complementary imaginary-quadrature outputs.','detector'),n('i','I difference',810,90,'Subtract 180° port from 0° port.'),n('q','Q difference',810,290,'Subtract 270° port from 90° port.')
],[e('sig','hybrid'),e('lo','hybrid'),e('hybrid','ip'),e('hybrid','qp'),e('ip','i','balanced difference','signal'),e('qp','q','balanced difference','signal')],['Identify two detector pairs, representing four actual photodiodes.','Compare I/Q gain imbalance and quadrature phase error before inferring a complex field.'],'No 90° hybrid or complex-field reconstruction is computed; phase labels specify an ideal design that requires calibration.',coherent),
record('FIELD-08','Spectral-domain OCT layer probe','A nominal 840 nm, 50 nm-bandwidth source feeds sample and reference arms; a spectrometer records their interferogram for depth reconstruction.',[
 n('source','840 nm / 50 nm source',90,190,'Broad bandwidth limits coherence length.'),n('split','Fiber coupler',290,190,'Splits into sample and reference arms.','bs'),n('sample','Layered specimen',490,90,'Reflections carry different optical path lengths.','sample'),n('reference','Reference mirror',490,290,'Adjust delay and match dispersion.','mirror'),n('spect','Interferogram spectrum',710,190,'Sample uniformly in wavenumber for reconstruction.','grating'),n('depth','Depth profile',880,190,'Fourier reconstruction needs refractive-index interpretation.')
],[e('source','split'),e('split','sample'),e('split','reference'),e('sample','split','backscatter'),e('reference','split','reference return'),e('split','spect'),e('spect','depth','k-linearized transform','signal')],['Separate optical depth from physical layer thickness.','Compare bandwidth-limited axial resolution with spectrometer sampling limits and dispersion mismatch.'],'This schematic does not compute a broadband interferogram or OCT reconstruction; an 840/50 nm Gaussian spectrum gives only a nominal approximately 6.2 µm air axial-resolution estimate.',ref('Thorlabs: OCT tutorial','https://www.thorlabs.com/images/pdf/octmanualrev7.pdf')),
record('FIELD-09','Two-aperture destructive nuller','Two equal-amplitude aperture feeds at 3.8 µm are combined with a π relative phase to reject an on-axis coherent source at the science port.',[
 n('a','Aperture A',90,90,'One collector of the on-axis source.'),n('b','Aperture B',90,290,'Second equal-amplitude collector.'),n('delay','Path equalizer',330,90,'Match optical path before phase bias.','delayline'),n('pi','π phase bias',330,290,'At 3.8 µm, π corresponds to 1.9 µm optical path.','phaseplate'),n('combine','Nulling combiner',580,190,'Matched amplitude, polarization and spatial modes.','bs'),n('dark','Dark science port',830,90,'On-axis coherent field is nominally suppressed.','detector'),n('bright','Bright monitor port',830,290,'Complementary port tracks total throughput.','detector')
],[e('a','delay'),e('b','pi'),e('delay','combine'),e('pi','combine'),e('combine','dark'),e('combine','bright')],['Compare the π phase bias with equal optical path before the bias.','Introduce amplitude or phase imbalance conceptually and identify why the dark port leaks.'],'Null depth, bandwidth, angular transmission and stellar leakage are not calculated; nominal phase cancellation is not high-contrast instrument proof.',ref('Asgard/NOTT authors: nulling interferometer optical design','https://arxiv.org/abs/2402.09013')),
record('FIELD-10','Two-telescope coherent aperture combination','Two separated telescope feeds are delay-matched and combined in K band; a fringe tracker controls delay while a science spectrometer records fringes.',[
 n('a','Telescope A',90,90,'First aperture on a chosen 50 m baseline.'),n('b','Telescope B',90,290,'Second aperture observes the same source.'),n('da','Feed A delay',330,90,'Compensates changing geometric path difference.','delayline'),n('db','Feed B relay',330,290,'Preserves the second aperture field.','lens'),n('comb','K-band combiner',580,190,'Chosen central wavelength 2.2 µm.','bs'),n('track','Fringe tracker',830,90,'Measures residual phase and commands delay correction.'),n('science','Science spectrometer',830,290,'Records spectrally dispersed coherent signal.','grating')
],[e('a','da'),e('b','db'),e('da','comb'),e('db','comb'),e('comb','track'),e('comb','science'),e('track','da','delay feedback','signal',[[830,65],[330,65]])],['Follow the delay feedback separately from the science output.','Compare a single baseline fringe measurement with complete aperture-synthesis image recovery.'],'No atmosphere, fringe tracking or aperture-synthesis reconstruction is simulated; baseline and wavelength describe an illustrative two-feed design.',ref('ESO: GRAVITY instrument subsystems','https://www.eso.org/sci/facilities/paranal/instruments/gravity/inst.html')),
];
