// SPDX-FileCopyrightText: 2026 Luca Genchi and contributors
// SPDX-License-Identifier: GPL-3.0-or-later
import '../../sketch/js/detector-instruments.js';
import { createElement } from '../../sketch/js/elements.js';

// Real registry components only: stable IDs and version-1 scenes are editable
// in the workbench. Parameters omitted here use the registry defaults.
function element(id, type, x, y, params, rot, label) {
  const base = createElement(type, x, y);
  return { ...base, id, rot, label, showLabel: true, params: { ...base.params, ...params } };
}

export const examples = [
  {
    id: "IMG-01",
    title: "Unit-magnification 4f relay",
    summary: "Two 100 mm thin lenses relay an object plane to an inverted image over 400 mm; the shared focal plane remains accessible.",
    steps: ["Open the live scene: the separately drawn ideal image of the 10 mm F is inverted at −1 magnification; the traced fan comes from the on-axis object anchor.","Move the camera 30 mm beyond its image conjugate: the narrow fan broadens and the camera no longer lies at the ideal image plane."],
    limit: "The fan traces on-axis geometrical rays, while the F marker is a separate paraxial image construction that does not model downstream clipping. No target-image irradiance, diffraction-limited transfer function or real-lens aberration is computed.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"},{"label":"MIT: spatial filtering lecture","url":"https://ocw.mit.edu/courses/2-71-optics-spring-2009/resources/mit2_71s09_lec18/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object", "objarrow", 80, 200, {"height":10,"shape":"F","spread":8,"nrays":7,"wavelength":532}, 0, "object"),
      element("first", "lens", 180, 200, {"dia":40}, 0, "first"),
      element("second", "lens", 380, 200, {"dia":40}, 0, "second"),
      element("image", "camera", 502, 200, {"ch":40}, 0, "image"),
    ], beams: [] },
  },
  {
    id: "IMG-02",
    title: "Threefold Keplerian beam expander",
    summary: "A 50 mm lens and a 150 mm lens, separated by 200 mm, expand a collimated 3 mm beam to approximately 9 mm.",
    steps: ["Open the ray example and compare beam width before and after the telescope.","Move L2 away from the 200 mm lens separation to see residual convergence or divergence."],
    limit: "This live example uses paraxial thin lenses; diffraction, real-lens aberrations and damage at the focus are absent.",
    references: [{"label":"Edmund Optics: laser beam expanders","url":"https://www.edmundoptics.com/knowledge-center/application-notes/lasers/beam-expanders"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {}, 0, "input"),
      element("first", "lens", 250, 200, {"f":50}, 0, "first"),
      element("second", "lens", 450, 200, {"f":150}, 0, "second"),
      element("output", "camera", 650, 200, {}, 0, "output"),
    ], beams: [] },
  },
  {
    id: "IMG-03",
    title: "Twofold pupil relay",
    summary: "A real galvo and 75/150 mm relay image its pivot onto a pupil-monitor camera. A 3 mm collimated beam expands to 6 mm in the relayed pupil.",
    steps: ["Read the pupil camera width with the galvo at zero mechanical angle.","Change galvo angle slightly and compare pivot conjugation with changing the relay lens spacing."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. The objective pupil is represented by the receiving camera plane; this is the pupil-relay subsystem, not a full microscope.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 60, 80, {}, 0, "input"),
      element("scanner", "galvo", 200, 80, {"length":30}, -45, "scanner"),
      element("first", "lens", 200, 155, {"f":75,"dia":40}, 90, "first"),
      element("second", "lens", 200, 380, {"f":150,"dia":40}, 90, "second"),
      element("pupil", "camera", 200, 552, {"ch":60,"interference":false}, 90, "pupil"),
    ], beams: [] },
  },
  {
    id: "IMG-04",
    title: "Infinity microscope with filter space",
    summary: "A generic 10× infinity objective faces a 2 mm object at its working-distance focus. A 200 mm tube lens and 550 nm filter deliver the ray bundle to a real camera.",
    steps: ["Follow the collimated region between objective and tube lens.","Change the tube lens focal length and move the camera to its new back-focal plane."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. Objective correction is a generic equivalent-lens model, not a manufacturer prescription.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object", "objarrow", 80, 200, {"height":2,"spread":6,"nrays":7,"wavelength":550}, 0, "object"),
      element("objective", "objective", 116, 200, {"efl":20,"workingDistance":20,"na":0.25}, 180, "objective"),
      element("filter", "filter", 210, 200, {"center":550}, 0, "filter"),
      element("tube", "lens", 320, 200, {"f":200,"dia":60}, 0, "tube"),
      element("image", "camera", 542, 200, {"ch":60,"interference":false}, 0, "image"),
    ], beams: [] },
  },
  {
    id: "IMG-05",
    title: "Object-space telecentric inspection",
    summary: "A 100 mm lens and a 2 mm stop at its rear focal plane form an object-space telecentric meridional relay. The off-axis emitting point is 200 mm before the lens.",
    steps: ["Inspect which object rays pass the rear-focal stop.","Move the stop away from x = 300 mm and compare the admitted chief-ray directions."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. A 1D slit is the meridional aperture section; no circular-pupil or unlimited-depth sharpness claim is made.",
    references: [{"label":"Edmund Optics: distortion and telecentricity","url":"https://www.edmundoptics.com/knowledge-center/application-notes/imaging/distortion-and-the-telecentricity-specification/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object", "objarrow", 0, 190, {"height":4,"spread":12,"nrays":9,"showImage":false,"wavelength":532}, 0, "object"),
      element("imaging", "lens", 200, 200, {"dia":60}, 0, "imaging"),
      element("rear-focal-stop", "slit", 300, 200, {"gap":2,"length":60}, 0, "rear-focal-stop"),
      element("image", "camera", 422, 200, {"ch":60,"interference":false}, 0, "image"),
    ], beams: [] },
  },
  {
    id: "IMG-06",
    title: "Folded two-mirror image relay",
    summary: "An actual two-conic Gregorian reflective relay carries a collimated 266 nm input through two reflections to a camera behind the perforated primary. Adapted from the native Gregorian example.",
    steps: ["Follow the first focus and returning secondary reflection.","Change the secondary radius or position and inspect focus broadening at the camera."],
    limit: "Exact conic intersections and reflected 2D rays are computed. No UV coating spectrum, diffraction or calibrated ultraviolet throughput is calculated.",
    references: [{"label":"NASA: reflective optics for ultraviolet imaging","url":"https://science.nasa.gov/mission/hubble/observatory/design/optics/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("uv-input", "cwlaser", 150, 190, {"wavelength":266,"beamWidth":54}, 0, "uv-input"),
      element("primary", "conicmirror", 500, 190, {"dia":55,"hole":15,"radius":-80,"conic":-1,"refl":96}, 0, "primary"),
      element("secondary", "conicmirror", 440, 190, {"dia":30,"radius":31.351351,"conic":-0.322133,"facing":"right","refl":96}, 0, "secondary"),
      element("uv-image", "camera", 534.5, 190, {"ch":20,"interference":false}, 0, "uv-image"),
    ], beams: [] },
  },
  {
    id: "IMG-07",
    title: "Tilted-plane inspection camera",
    summary: "Three emitting points lie on a plane tilted 26.565° in the meridional section. A 100 mm lens images them onto a camera plane tilted by the opposite geometric slope.",
    steps: ["Follow the three narrow ray bundles to distinct positions on the tilted sensor.","Set the camera rotation to zero and compare the off-axis bundle widths at the now incorrect plane."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. This is a three-point plane-conjugacy example; it does not render a continuous tilted target or predict depth of field.",
    references: [{"label":"Edmund Optics: distortion and telecentricity","url":"https://www.edmundoptics.com/knowledge-center/application-notes/imaging/distortion-and-the-telecentricity-specification/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("upper-point", "objarrow", -10, 180, {"height":2,"spread":8,"nrays":7,"showImage":false}, 0, "upper-point"),
      element("center-point", "objarrow", 0, 200, {"height":2,"spread":8,"nrays":7,"showImage":false}, 0, "center-point"),
      element("lower-point", "objarrow", 10, 220, {"height":2,"spread":8,"nrays":7,"showImage":false}, 0, "lower-point"),
      element("imaging", "lens", 200, 200, {"dia":80}, 0, "imaging"),
      element("tilted-sensor", "camera", 419.67739820199813, 209.83869910099907, {"ch":80,"interference":false}, 26.56505117707799, "tilted-sensor"),
    ], beams: [] },
  },
  {
    id: "IMG-08",
    title: "K-mirror field derotator",
    summary: "Three plane mirrors on one rotating mount derotate an astronomical field; a 15° mechanical rotation corresponds to a nominal 30° image rotation.",
    steps: ["Follow the three reflections rather than interpreting the folded path as an image rotation simulation.","Compare the nominal twice-angle image rotation with the mount angle."],
    limit: "Image parity and 3D field rotation require a coordinate convention; the 2D diagram cannot calculate a derotated image.",
    references: [{"label":"ESO: SPHERE instrument description and derotator","url":"https://www.eso.org/sci/facilities/paranal/instruments/sphere/inst.html"}],
    mode: "unavailable",
    unavailableReason: "The registry has no 3D K-mirror image rotator or transverse image-field rotation. Three coplanar mirrors can fold a ray but cannot demonstrate this indispensable out-of-plane image rotation in a 2D scene.",
  },
  {
    id: "IMG-09",
    title: "Two-group compensated zoom",
    summary: "Two native lens-group endpoints share a fixed 400 mm object-to-image distance: 1× with lens positions 100/300 mm, and 2× with positions 29.289/158.579 mm relative to the object.",
    steps: ["Compare the two camera faces, both 400 mm from their object plane.","Inspect the separate lens translations needed for the 2× endpoint; moving only one group loses the shared image plane."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. Only two solved endpoints are supplied; continuous motion control, aberration correction and a production zoom prescription are not supplied.",
    references: [{"label":"Canon: zoom variator and compensator white paper","url":"https://downloads.canon.com/bctv/4K_Box_Lenses_White_Paper.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object-1x", "objarrow", 80, 120, {"height":4,"shape":"F","spread":8,"nrays":7,"wavelength":532}, 0, "object · 1×"),
      element("first-1x", "lens", 180, 120, {"dia":50}, 0, "first · 1×"),
      element("second-1x", "lens", 380, 120, {"dia":50}, 0, "second · 1×"),
      element("image-1x", "camera", 502, 120, {"ch":60,"interference":false}, 0, "image · 1×"),
      element("object-2x", "objarrow", 80, 350, {"height":4,"shape":"F","spread":4,"nrays":7,"wavelength":532}, 0, "object-2x"),
      element("variator-2x", "lens", 109.28932188134524, 350, {"dia":50}, 0, "variator-2x"),
      element("compensator-2x", "lens", 238.5786437626905, 350, {"dia":50}, 0, "compensator-2x"),
      element("image-2x", "camera", 502, 350, {"ch":60,"interference":false}, 0, "image-2x"),
    ], beams: [] },
  },
  {
    id: "BEAM-01",
    title: "Pinhole spatial filter",
    summary: "A native 20 mm focusing lens, 0.5 mm meridional focal aperture and 100 mm recollimator form a physical spatial-filter bench at 532 nm.",
    steps: ["Inspect the tight geometric focus through the slit aperture.","Shift the aperture away from the axis and compare transmitted power."],
    limit: "The slit represents a pinhole cross-section in 2D. Geometric clipping and recollimation are traced; Airy diffraction, coherent spatial-frequency cleaning and damage are not predicted.",
    references: [{"label":"Newport: spatial filters","url":"https://www.newport.com/n/spatial-filters"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":2}, 0, "input"),
      element("focus", "lens", 200, 200, {"f":20,"dia":20}, 0, "focus"),
      element("focal-aperture", "slit", 220, 200, {"gap":0.5,"length":30}, 0, "slit"),
      element("recollimator", "lens", 320, 200, {"dia":30}, 0, "recollimator"),
      element("output", "camera", 500, 200, {"ch":60,"interference":false}, 0, "output"),
    ], beams: [] },
  },
  {
    id: "BEAM-02",
    title: "Fiber spatial-mode filter",
    summary: "A 780 nm input is focused into a propagating native fiber link and recollimated at its output. The fiber follows an actual routed path with NA acceptance and attenuation.",
    steps: ["Follow coupling into the fiber at x = 180 mm and the emitted output at x = 420 mm.","Tilt the entry segment outside the acceptance cone and compare output collection."],
    limit: "The native fiber computes geometrical acceptance, transport and specified output NA. It does not compute a Gaussian mode-overlap integral, cutoff wavelength or single-mode purity; single-mode filtering is the physical design intent.",
    references: [{"label":"Thorlabs: single-mode fiber coupling","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=1421"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 40, 190, {"wavelength":780,"beamWidth":6}, 0, "input"),
      element("coupler", "lens", 150, 190, {"f":30,"dia":20}, 0, "coupler"),
      element("output-collimator", "lens", 440, 260, {"f":20,"dia":30}, 0, "collimator"),
      element("output", "camera", 570, 260, {"ch":60,"interference":false}, 0, "output"),
    ], beams: [{"id":"mode-filter-fiber","kind":"fiber","bare":false,"propagate":true,"color":"#e8a800","width":4,"pts":[{"x":180,"y":190},{"x":250,"y":190},{"x":350,"y":260},{"x":420,"y":260}],"inputNA":0.22,"groupIndex":1.468,"lossDbPerM":0.2,"out0":{"mode":"diverge","na":0.12,"focal":20,"dia":6},"out1":{"mode":"diverge","na":0.12,"focal":20,"dia":6}}] },
  },
  {
    id: "BEAM-03",
    title: "Two-lens cavity mode matching",
    summary: "A real two-lens 1064 nm injection train changes a collimated 6 mm beam into a converging bundle. The receiving camera inspects the chosen waist plane before a prospective cavity input.",
    steps: ["Read the profile near the receiving waist plane.","Translate the second lens and compare both waist position and size at the fixed camera."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. This is the adjustable injection-optics subsystem; no cavity eigenmode or Gaussian overlap efficiency is inferred from a ray waist.",
    references: [{"label":"Newport: cavity mode matching appendix","url":"https://www.newport.com/medias/sys_master/images/images/h73/he8/8797035429918/9091-User-Manual-RevD.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 40, 200, {"wavelength":1064,"beamWidth":6}, 0, "input"),
      element("waist-control", "lens", 180, 200, {"dia":40}, 0, "L1"),
      element("injection", "lens", 250, 200, {"f":50,"dia":30}, 0, "L2"),
      element("waist-plane", "camera", 290.75, 200, {"ch":60,"interference":false}, 0, "waist"),
    ], beams: [] },
  },
  {
    id: "BEAM-04",
    title: "Cylindrical 4× anamorphic expander",
    summary: "The powered meridian of a 25/100 mm cylindrical telescope is represented by native ideal lenses separated by 125 mm. Rays expand from 2 to 8 mm along the modeled axis.",
    steps: ["Compare input and output width in the powered meridional section.","Change lens separation to see residual convergence; the orthogonal unpowered axis is outside this 2D scene."],
    limit: "The native ideal lenses represent the powered cross-section of cylindrical optics. The unpowered transverse axis, astigmatism and a complete 2D beam cross-section are not simulated.",
    references: [{"label":"Edmund Optics: laser beam expanders","url":"https://www.edmundoptics.com/knowledge-center/application-notes/lasers/beam-expanders"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":2}, 0, "input"),
      element("powered-meridian-C1", "lens", 220, 200, {"f":25,"dia":30}, 0, "powered-meridian-C1"),
      element("powered-meridian-C2", "lens", 345, 200, {"dia":40}, 0, "powered-meridian-C2"),
      element("expanded-meridian", "camera", 520, 200, {"ch":60,"interference":false}, 0, "expanded-meridian"),
    ], beams: [] },
  },
  {
    id: "BEAM-05",
    title: "Gaussian-to-top-hat refractive mapper",
    summary: "Two aspheric surfaces redistribute a nominal 3 mm radius Gaussian input into a 4 mm radius flat-top output without deliberately clipping the center.",
    steps: ["Compare redistribution with lossy aperture truncation.","Change the assumed input radius and identify why a fixed remapper will no longer produce its design profile."],
    limit: "Generic asphere icons do not supply a solved remapping prescription; no top-hat irradiance is simulated.",
    references: [{"label":"Newport: refractive beam shaping","url":"https://www.newport.com/medias/sys_master/images/images/h0f/hab/8797246685214/Refractive-Beam-Shaper-Application-Note.pdf"}],
    mode: "unavailable",
    unavailableReason: "The source lacks a spatial Gaussian irradiance distribution and the registry has no solved two-surface Gaussian-to-top-hat energy-remapping prescription. Ordinary lenses or unsolved aspheres cannot demonstrate the required irradiance mapping.",
  },
  {
    id: "BEAM-06",
    title: "Fly-eye homogenizer",
    summary: "Two real three-lens arrays form three meridional beamlet channels, followed by a 100 mm field lens. The camera receives their overlapping geometrical contributions.",
    steps: ["Follow each lenslet channel through both arrays and the field lens.","Move one second-array lenslet transversely and inspect loss of common overlap."],
    limit: "The arrays are actual separate native lenses in one meridional section. Beamlet paths and overlap are computed; coherent speckle, 2D fly-eye uniformity and microlens diffraction are not.",
    references: [{"label":"Edmund Optics: microlens arrays","url":"https://www.edmundoptics.com/f/microlens-arrays/13812/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":30}, 0, "input"),
      element("array-A-1", "lens", 200, 190, {"f":50,"dia":10}, 0, "array-A-1"),
      element("array-A-2", "lens", 200, 200, {"f":50,"dia":10}, 0, "array-A-2"),
      element("array-A-3", "lens", 200, 210, {"f":50,"dia":10}, 0, "array-A-3"),
      element("array-B-1", "lens", 250, 190, {"f":50,"dia":10}, 0, "array-B-1"),
      element("array-B-2", "lens", 250, 200, {"f":50,"dia":10}, 0, "array-B-2"),
      element("array-B-3", "lens", 250, 210, {"f":50,"dia":10}, 0, "array-B-3"),
      element("field-lens", "lens", 350, 200, {"dia":80}, 0, "field-lens"),
      element("overlap-field", "camera", 472, 200, {"ch":100,"interference":false}, 0, "overlap-field"),
    ], beams: [] },
  },
  {
    id: "BEAM-07",
    title: "4f low-pass spatial filter",
    summary: "A real 100/100 mm 4f relay exposes its common focal plane at x = 280 mm. A native 8 mm slit at that plane selects angular content before the image camera.",
    steps: ["Locate the aperture at the shared focal plane, separate from the object and camera planes.","Reduce slit gap and compare transmitted ray angles and camera power."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. The optical layout is real; the tracer does not Fourier-transform a target image or calculate low-pass image contrast.",
    references: [{"label":"MIT: spatial filtering lecture","url":"https://ocw.mit.edu/courses/2-71-optics-spring-2009/resources/mit2_71s09_lec18/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object", "objarrow", 80, 200, {"height":4,"shape":"F","spread":8,"nrays":7,"wavelength":532}, 0, "object"),
      element("first", "lens", 180, 200, {"dia":50}, 0, "first"),
      element("second", "lens", 380, 200, {"dia":50}, 0, "second"),
      element("image", "camera", 502, 200, {"ch":60,"interference":false}, 0, "image"),
      element("fourier-stop", "slit", 280, 200, {"length":60}, 0, "fourier-stop"),
    ], beams: [] },
  },
  {
    id: "BEAM-08",
    title: "SLM hologram with order selection",
    summary: "A native transmissive SLM with a programmed two-lenslet layer directs a 24 mm beam into two geometrical focal spots 80 mm downstream.",
    steps: ["Inspect the two focal channels and their camera profile.","Change the lens-array layer to three lenslets or adjust focal length; the traced paths update directly."],
    limit: "Native SLM phase-gradient functions steer and focus rays. The scene does not synthesize a phase hologram, compute coherent order efficiency or validate equal spot irradiance.",
    references: [{"label":"Hamamatsu: wavefront modulation research","url":"https://www.hamamatsu.com/us/en/our-company/business-domain/central-research-laboratory/optical-information-processing-and-measurement/wave.html"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":24}, 0, "input"),
      element("programmable-SLM", "slm", 250, 200, {"transmissive":true,"length":24,"layers":[{"type":"lensarray","n":2,"f":80}]}, 0, "SLM"),
      element("target", "camera", 343, 200, {"ch":40,"interference":false}, 0, "target"),
    ], beams: [] },
  },
  {
    id: "ILL-01",
    title: "Köhler transmitted-light microscope",
    summary: "Three native point emitters sample an extended lamp. A 25.455 mm collector conjugates the lamp to the condenser front focal plane; the field stop is conjugate to the specimen camera.",
    steps: ["Compare the field stop at x = 140 mm with the angular aperture at x = 190 mm.","Change either stop gap independently and inspect the admitted ray bundles."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. The three-point lamp is a discrete extended-source sample, not a uniform illumination calculation.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("filament-1", "pointsource", 80, 197, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-1"),
      element("filament-2", "pointsource", 80, 200, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-2"),
      element("filament-3", "pointsource", 80, 203, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-3"),
      element("collector", "lens", 120, 200, {"f":25.454545454545453,"dia":40}, 0, "collector"),
      element("field-stop", "slit", 140, 200, {"gap":20,"length":60}, 0, "field-stop"),
      element("aperture-stop", "slit", 190, 200, {"gap":6,"length":60}, 0, "aperture-stop"),
      element("condenser", "lens", 240, 200, {"f":50,"dia":40}, 0, "condenser"),
      element("specimen-plane", "camera", 362, 200, {"ch":60,"interference":false}, 0, "specimen-plane"),
    ], beams: [] },
  },
  {
    id: "ILL-02",
    title: "Critical LED illumination",
    summary: "Three lamp points are directly imaged at unit magnification by a 20 mm condenser onto a specimen-plane camera 40 mm behind it.",
    steps: ["Inspect the three distinct lamp-point images.","Compare moving the lamp with moving the camera away from the 2f conjugate."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. Lamp structure is sampled by three emitters; surface irradiance and uniformity are not calibrated.",
    references: [{"label":"Nikon: critical illumination","url":"https://www.microscopyu.com/glossary/critical-illumination"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("filament-1", "pointsource", 80, 197, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-1"),
      element("filament-2", "pointsource", 80, 200, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-2"),
      element("filament-3", "pointsource", 80, 203, {"wavelength":550,"spread":16,"nrays":7}, 0, "filament-3"),
      element("critical-condenser", "lens", 120, 200, {"f":20,"dia":40}, 0, "critical-condenser"),
      element("source-image", "camera", 182, 200, {"ch":60,"interference":false}, 0, "source-image"),
    ], beams: [] },
  },
  {
    id: "ILL-03",
    title: "488 nm epi-fluorescence microscope",
    summary: "A native 488 nm excitation beam reflects downward through a shared objective. A fluorescent sample generates 520 nm return light that passes the dichroic and emission filter into the camera.",
    steps: ["Identify the wavelengths before and after the specimen.","Change the emission filter center to reject the fluorescent return."],
    limit: "The sample emits qualitative isotropic fluorescence. Objective acceptance and spectral routing are traced; fluorescence microscopy resolution, collection calibration and quantum yield are not predicted.",
    references: [{"label":"Nikon: fluorescence filter combinations","url":"https://www.microscopyu.com/techniques/fluorescence/fluorescence-filter-combinations"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("excitation", "cwlaser", 80, 100, {"wavelength":488,"beamWidth":2}, 0, "excitation"),
      element("dichroic", "dichroic", 300, 100, {"cutoff":500,"length":40}, -45, "dichroic"),
      element("objective", "objective", 300, 220, {"efl":20,"workingDistance":20,"na":0.25}, 90, "objective"),
      element("specimen", "sample", 300, 256, {"specimenType":"linear","channels":[{"kind":"fluor","wl":520,"eff":0.5,"fluorophore":"custom","band":10}],"transmitExc":false}, 0, "specimen"),
      element("emission-filter", "filter", 300, 30, {"center":520}, 90, "emission-filter"),
      element("emission-camera", "camera", 300, -60, {"ch":60,"interference":false}, -90, "emission-camera"),
    ], beams: [] },
  },
  {
    id: "ILL-04",
    title: "Annular pupil illumination",
    summary: "Real opaque masks admit the two meridional sections of an annular pupil, between 9 and 12 mm from the axis. A condenser brings the oblique ray bundles to the specimen camera.",
    steps: ["Follow the blocked central beam and the two surviving pupil bands.","Increase the central obscuration and compare transmitted power."],
    limit: "This is an actual 2D cross-section of annular illumination. A complete azimuthal cone, scattering contrast and dark-field specimen response require 3D scattering and are not calculated.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":30}, 0, "input"),
      element("central-obscuration", "beamdump", 200, 200, {"aperture":18}, 0, "central-obscuration"),
      element("upper-mask", "beamdump", 200, 173, {"aperture":26}, 0, "upper-mask"),
      element("lower-mask", "beamdump", 200, 227, {"aperture":26}, 0, "lower-mask"),
      element("condenser", "lens", 250, 200, {"dia":60}, 0, "condenser"),
      element("specimen-plane", "camera", 372, 200, {"ch":60,"interference":false}, 0, "specimen-plane"),
    ], beams: [] },
  },
  {
    id: "ILL-05",
    title: "Three-phase stripe projection",
    summary: "A real binary DMD selects a 10 mm pitch ON pattern and directs it downward through a 75 mm projection lens. The tilted receiving camera follows the tilted modulator-plane conjugacy.",
    steps: ["Inspect the surviving ON pattern and absorbed OFF regions.","Translate the DMD by one third pitch along its active surface to compare the next phase position; keep the camera conjugate aligned."],
    limit: "Native binary micromirror routing and geometric projection are traced. No sinusoidal fringe synthesis, three-frame phase reconstruction, diffraction orders or structured-illumination resolution gain is calculated.",
    references: [{"label":"Gustafsson: structured illumination beyond the classical resolution limit","url":"https://doi.org/10.1046/j.1365-2818.2000.00710.x"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("pattern-illumination", "cwlaser", 60, 207.54803511150882, {"beamWidth":40}, 0, "pattern-illumination"),
      element("binary-DMD", "dmd", 300, 200, {"length":80,"pitch":10}, -57, "binary-DMD"),
      element("projection-lens", "lens", 295.09824868486476, 357.54803511150885, {"f":75,"dia":80}, 90, "projection-lens"),
      element("tilted-pattern-camera", "camera", 307.08030745519534, 525.9987876063082, {"ch":100,"interference":false}, 57, "tilted-pattern-camera"),
    ], beams: [] },
  },
  {
    id: "ILL-06",
    title: "Orthogonal light-sheet microscope",
    summary: "A real focusing meridian illuminates a fluorescent sample from the side while an orthogonal objective and tube lens collect its emitted signal above. The illumination lens represents a cylindrical powered section.",
    steps: ["Follow the independent illumination and collection axes.","Move the fluorescence sample away from the illumination focus and inspect geometric overlap."],
    limit: "Native rays demonstrate an orthogonal illumination/detection section. The second transverse axis, actual sheet extent and thickness, diffraction-limited sectioning and volumetric reconstruction are not available in this 2D scene.",
    references: [{"label":"Huisken et al.: selective plane illumination microscopy","url":"https://doi.org/10.1126/science.1100035"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("sheet-meridian", "cwlaser", 60, 200, {"beamWidth":10}, 0, "sheet-meridian"),
      element("cylindrical-powered-meridian", "lens", 200, 200, {"dia":30}, 0, "cylindrical-powered-meridian"),
      element("illuminated-section", "sample", 300, 200, {"specimenType":"linear","channels":[{"kind":"fluor","wl":520,"eff":0.5,"fluorophore":"custom","band":10}],"transmitExc":false}, 90, "illuminated-section"),
      element("detection-objective", "objective", 300, 164, {"efl":20,"workingDistance":20,"na":0.6,"frontAperture":30}, 90, "detection-objective"),
      element("detection-tube", "lens", 300, 60, {"dia":50}, 90, "detection-tube"),
      element("orthogonal-detector", "camera", 300, -62, {"ch":60,"interference":false}, -90, "orthogonal-detector"),
    ], beams: [] },
  },
  {
    id: "ILL-07",
    title: "Fourfold reduction exposure",
    summary: "A real 200/50 mm relay projects a native object with quarter-scale ideal magnification onto the camera. The long first focal length and shorter second focal length create the reduction.",
    steps: ["Compare the paraxial object marker size with the original 10 mm object.","Change the camera position and inspect the loss of conjugacy."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. This is the projection subsystem; no digital spatial modulator or calibrated image brightness is simulated.",
    references: [{"label":"ASML: TWINSCAN NXT:1965Ci reduction projection system","url":"https://www.asml.com/en/products/duv-lithography-systems/twinscan-nxt-1965ci"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("object", "objarrow", 80, 200, {"height":10,"shape":"F","spread":8,"nrays":7,"wavelength":532}, 0, "object"),
      element("first", "lens", 280, 200, {"f":200,"dia":50}, 0, "first"),
      element("second", "lens", 530, 200, {"f":50,"dia":50}, 0, "second"),
      element("image", "camera", 602, 200, {"ch":60,"interference":false}, 0, "image"),
    ], beams: [] },
  },
  {
    id: "ILL-08",
    title: "Four-spot microlens illuminator",
    summary: "Four actual 50 mm lenslets form four focal spots in a line on a camera. This is a meridional four-spot illuminator rather than a simulated second transverse row.",
    steps: ["Count the four lenslets and follow each independent focus.","Change one focal length to move that channel away from the shared focal plane."],
    limit: "Four geometric channels and focal positions are traced. A 2×2 spot grid, microlens diffraction and equal-irradiance calibration require a second transverse axis and wave modeling.",
    references: [{"label":"Edmund Optics: microlens arrays","url":"https://www.edmundoptics.com/f/microlens-arrays/13812/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":40}, 0, "input"),
      element("lenslet-1", "lens", 200, 185, {"f":50,"dia":10}, 0, "lenslet-1"),
      element("lenslet-2", "lens", 200, 195, {"f":50,"dia":10}, 0, "lenslet-2"),
      element("lenslet-3", "lens", 200, 205, {"f":50,"dia":10}, 0, "lenslet-3"),
      element("lenslet-4", "lens", 200, 215, {"f":50,"dia":10}, 0, "lenslet-4"),
      element("four-spot-plane", "camera", 272, 200, {"ch":60,"interference":false}, 0, "four-spot-plane"),
    ], beams: [] },
  },
  {
    id: "SCAN-01",
    title: "Single-axis pupil-conjugate scanner",
    summary: "A real galvo feeds a 75/75 mm pupil relay and a fixed generic objective. The camera monitors the focused meridional scan.",
    steps: ["Change the galvo command by a small mechanical angle and inspect focal displacement.","Move a relay lens and compare the pupil walk and collection."],
    limit: "Native 2D geometrical rays are computed. Diffraction, target-image irradiance and real-lens aberrations are not calculated; ideal object-image markers are separate paraxial constructions. Objective pupils and high-NA field distortion are generic; the setup does not calibrate a commercial scanner.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"},{"label":"Thorlabs: scanning lenses","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=2910"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 60, 80, {}, 0, "input"),
      element("scanner", "galvo", 200, 80, {"length":30}, -45, "scanner"),
      element("relay-first", "lens", 200, 155, {"f":75,"dia":40}, 90, "relay-first"),
      element("relay-second", "lens", 200, 305, {"f":75,"dia":40}, 90, "relay-second"),
      element("scan-objective", "objective", 200, 380, {"efl":20,"workingDistance":20,"na":0.25}, 90, "scan-objective"),
      element("scan-plane", "camera", 200, 438, {"ch":40,"interference":false}, 90, "scan-plane"),
    ], beams: [] },
  },
  {
    id: "SCAN-02",
    title: "Relayed X and Y galvos",
    summary: "A 75/75 mm 4f relay images the X-galvo pivot onto the Y-galvo pivot before a second relay to the objective pupil.",
    steps: ["Compare relayed galvos with two nearby but nonconjugate mirrors.","Check that both pivots map to the objective pupil before discussing a 2D raster."],
    limit: "Orthogonal scan axes are shown topologically; the 2D ray editor cannot represent the full two-axis raster simultaneously.",
    references: [{"label":"Nikon: conjugate planes in optical microscopy","url":"https://www.microscopyu.com/microscopy-basics/conjugate-planes-in-optical-microscopy"}],
    mode: "unavailable",
    unavailableReason: "Independent orthogonal galvo axes and their conjugate pupil mapping require a second transverse coordinate and out-of-plane mirror orientation. Two native coplanar galvos cannot demonstrate a true X/Y raster.",
  },
  {
    id: "SCAN-03",
    title: "Confocal scan and descan return",
    summary: "Native excitation and fluorescent return use the same galvo and objective. The dichroic separates emitted light toward a stationary 0.5 mm slit and detector.",
    steps: ["Follow the wavelength-changing return through the same scanner.","Move the detection slit laterally and compare accepted fluorescence."],
    limit: "A physical shared-path scan/descan bench is traced with qualitative fluorescence. A 1D slit is the pinhole section; confocal PSF, continuous specimen scanning and calibrated optical sectioning are not computed.",
    references: [{"label":"Nikon: confocal scanning optical systems","url":"https://www.microscopyu.com/techniques/confocal/confocal-microscope-scanning-systems"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("excitation", "cwlaser", 80, 100, {"wavelength":488,"beamWidth":2}, 0, "excitation"),
      element("dichroic", "dichroic", 300, 100, {"cutoff":500,"length":40}, -45, "dichroic"),
      element("shared-scanner", "galvo", 300, 200, {"length":40}, 45, "shared-scanner"),
      element("objective", "objective", 180, 200, {"efl":20,"workingDistance":20,"na":0.25}, 180, "objective"),
      element("specimen", "sample", 144, 200, {"specimenType":"linear","channels":[{"kind":"fluor","wl":520,"eff":0.5,"fluorophore":"custom","band":10}],"transmitExc":false}, 90, "specimen"),
      element("emission-filter", "filter", 300, 60, {"center":520}, 90, "emission-filter"),
      element("return-focus", "lens", 300, 30, {"f":50,"dia":50}, 90, "return-focus"),
      element("detection-pinhole", "slit", 300, -20, {"gap":0.5,"length":50}, 90, "detection-pinhole"),
      element("return-detector", "detector", 300, -100, {}, -90, "return-detector"),
    ], beams: [] },
  },
  {
    id: "SCAN-04",
    title: "100 mm f-theta processing head",
    summary: "A nominal 100 mm f-theta lens maps ±5° optical scan angles to approximately ±8.73 mm of target displacement.",
    steps: ["Calculate 100 × 5π/180 mm and distinguish optical angle from mechanical galvo angle.","Compare ideal fθ placement with measured field distortion and focus variation."],
    limit: "The thin-lens icon is not an f-theta prescription; no flat-field correction, process dose or calibrated scan is simulated.",
    references: [{"label":"Thorlabs: scanning lenses","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=2910"}],
    mode: "unavailable",
    unavailableReason: "The registry has no f-theta scan-lens prescription or distortion law x = fθ. Its native ideal thin lens instead maps the meridional angle approximately as f tanθ and cannot demonstrate the specified flat-field f-theta correction.",
  },
  {
    id: "SCAN-05",
    title: "Remote mirror focus translation",
    summary: "A real objective focuses onto a remote end mirror; its return is split downward into a stationary second objective and camera. The end mirror can be translated independently.",
    steps: ["Trace both passes through the remote objective.","Translate the remote mirror and inspect the changed return focus at the fixed camera."],
    limit: "The native generic objectives demonstrate geometric remote focus. Refractive-index pupil matching, high-NA aberration cancellation and calibrated axial magnification are not modeled.",
    references: [{"label":"Botcherby et al.: aberration-free optical refocusing","url":"https://doi.org/10.1016/j.optcom.2007.10.007"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {}, 0, "input"),
      element("return-separator", "bs", 300, 200, {}, 0, "return-separator"),
      element("remote-objective", "objective", 450, 200, {"efl":20,"workingDistance":20,"na":0.25}, 0, "remote-objective"),
      element("remote-mirror", "mirror", 486, 200, {"length":30}, 0, "remote-mirror"),
      element("specimen-objective", "objective", 300, 350, {"efl":20,"workingDistance":20,"na":0.25}, 90, "specimen-objective"),
      element("specimen-plane", "camera", 300, 408, {"ch":40,"interference":false}, 90, "specimen-plane"),
    ], beams: [] },
  },
  {
    id: "SCAN-06",
    title: "Moving-retroreflector delay stage",
    summary: "A native pulsed beam enters a real retroreflector 20 mm above its center and returns on a separate fixed axis 20 mm below. Translating the retroreflector changes the round-trip length.",
    steps: ["Inspect the distinct input and return axes.","Translate the retroreflector 15 mm right: free-space propagation gains 30 mm, about 100 ps."],
    limit: "Native retroreflection and pulsed propagation are traced. Carriage mechanics, air-index dispersion and stage accuracy are not simulated.",
    references: [{"label":"ESO: VLTI delay-line subsystem","url":"https://www.eso.org/sci/facilities/paranal/telescopes/vlti/subsystems/delaylines.html"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "pulsedlaser", 80, 180, {"wavelength":800,"beamMode":"line"}, 0, "input"),
      element("moving-retroreflector", "retroreflector", 400, 200, {"length":100}, 0, "moving-retroreflector"),
      element("fixed-return", "detector", 200, 220, {}, 180, "fixed-return"),
    ], beams: [] },
  },
  {
    id: "SCAN-07",
    title: "80 MHz double-pass AOM",
    summary: "A cat-eye return traverses an 80 MHz AOM twice; polarization separation extracts a nominal +160 MHz output while suppressing pointing sensitivity.",
    steps: ["Count two frequency shifts in the selected order.","Follow the cat-eye return and identify why the extracted output uses the other PBS port."],
    limit: "The diagram does not calculate RF frequency shifts, cat-eye alignment or frequency-dependent output pointing; the quarter-wave element is described at the end mirror.",
    references: [{"label":"Donley et al., NIST: compact double-pass AOM","url":"https://www.nist.gov/publications/compact-double-pass-acousto-optic-modulator-system"}],
    mode: "unavailable",
    unavailableReason: "The native AOM does not compute optical-frequency shifts or the bidirectional diffraction-order relation required for a +160 MHz double-pass cat-eye output. A pair of bent ray paths would not demonstrate frequency doubling or pointing compensation.",
  },
  {
    id: "SCAN-08",
    title: "Herriott-cell multipass absorption",
    summary: "Two concave mirrors repeatedly pass a beam through a 200 mm gas cell before the selected exit aperture reaches a detector.",
    steps: ["Count physical traversals rather than multiplying by the number of mirror spots without checking the sequence.","Distinguish a finite multipass orbit with an exit hole from a resonant cavity."],
    limit: "Mirror separation and curvature alone do not specify the 3D Herriott orbit; no gas-line absorption spectrum or spot sequence is calculated.",
    references: [{"label":"Herriott et al.: off-axis paths in spherical-mirror interferometers","url":"https://doi.org/10.1364/AO.3.000523"}],
    mode: "unavailable",
    unavailableReason: "A true Herriott cell needs the two-transverse-axis off-axis spot orbit and independently placed entrance/exit mirror holes. The 2D mirror model only supplies a central hole and cannot represent the indispensable selected 3D exit spot.",
  },
  {
    id: "ROUTE-01",
    title: "Two-color dichroic splitter",
    summary: "Spatially separate 488 and 640 nm native lasers are combined by a first 550 nm dichroic. A second dichroic separates their common beam into two wavelength-selective detector ports.",
    steps: ["Follow the two physically separate source inputs into the shared axis.","Move the second dichroic cutoff below 488 nm to send both colors to the transmitted detector."],
    limit: "The native dichroic model uses ideal wavelength bands; angle-dependent coating spectra, transition width and leakage are absent.",
    references: [{"label":"Edmund Optics: optical beamsplitter selection","url":"https://www.edmundoptics.com/c/beamsplitters/622/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("red-input", "cwlaser", 70, 200, {"wavelength":640,"beamMode":"line","beamWidth":6}, 0, "red-input"),
      element("blue-input", "cwlaser", 200, 80, {"wavelength":488,"beamMode":"line","beamWidth":6}, 90, "blue-input"),
      element("input-combiner", "dichroic", 200, 200, {"length":40}, -45, "input-combiner"),
      element("dichroic", "dichroic", 350, 200, {"length":40}, -45, "dichroic"),
      element("red-output", "detector", 600, 200, {}, 0, "red-output"),
      element("blue-output", "detector", 350, 400, {}, 90, "blue-output"),
    ], beams: [] },
  },
  {
    id: "ROUTE-02",
    title: "Equal-power polarization splitter",
    summary: "A 532 nm beam with linear polarization at 45° enters a PBS and divides into orthogonal polarization channels.",
    steps: ["Compare detector powers and polarization states in the traced example.","Set input polarization to 0° or 90° and verify extinction of the complementary port."],
    limit: "Ideal Stokes projection is traced; finite PBS extinction, coating phase and depolarization are absent.",
    references: [{"label":"Edmund Optics: polarizing beamsplitters","url":"https://www.edmundoptics.com/c/polarizing-beamsplitters/701/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamMode":"line","pol":45}, 0, "input"),
      element("splitter", "pbs", 350, 200, {}, 90, "splitter"),
      element("transmitted", "detector", 600, 200, {}, 0, "transmitted"),
      element("reflected", "detector", 350, 400, {}, 90, "reflected"),
    ], beams: [] },
  },
  {
    id: "ROUTE-03",
    title: "Half-wave power attenuator",
    summary: "A half-wave plate at 22.5° rotates a horizontal 532 nm input to 45°; a horizontal analyzer passes half the input power.",
    steps: ["Read half-power transmission at 22.5° in the live scene.","Rotate the HWP to 0° and 45° to compare full transmission and extinction."],
    limit: "Ideal retardance and Malus-law attenuation are traced; absorption heating and wavelength-dependent plate errors are absent.",
    references: [{"label":"Thorlabs: waveplate tutorial","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7234&tabname=Tutorial"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamMode":"line"}, 0, "input"),
      element("plate", "hwp", 250, 200, {}, 0, "plate"),
      element("analyzer", "polarizer", 400, 200, {}, 0, "analyzer"),
      element("output", "detector", 600, 200, {}, 0, "output"),
    ], beams: [] },
  },
  {
    id: "ROUTE-04",
    title: "Quarter-wave shared-aperture return",
    summary: "A native PBS passes horizontal light through a 45° quarter-wave plate to a mirror. The double pass changes the return polarization and directs it to the receive detector.",
    steps: ["Count two actual traversals of the quarter-wave plate.","Rotate its fast axis to 0° and compare extinction of the receive port."],
    limit: "Native Stokes retardance and specular return routing are computed. A rough or depolarizing target, coating phase and certified extinction are not modeled.",
    references: [{"label":"Thorlabs: waveplate tutorial","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7234&tabname=Tutorial"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamMode":"line","beamWidth":6}, 0, "input"),
      element("send-return-PBS", "pbs", 200, 200, {}, 0, "send-return-PBS"),
      element("double-pass-QWP", "qwp", 300, 200, {}, 0, "double-pass-QWP"),
      element("reflecting-target", "mirror", 400, 200, {"length":40}, 0, "reflecting-target"),
      element("receive", "detector", 200, 350, {}, 90, "receive"),
    ], beams: [] },
  },
  {
    id: "ROUTE-05",
    title: "Faraday isolator for laser protection",
    summary: "Two native test rows demonstrate the isolator directional gate: the forward source reaches its camera, while an independent backward source is stopped.",
    steps: ["Compare the forward camera with the blocked reverse test row.","Reverse the isolator orientation and inspect which test direction is admitted."],
    limit: "The registry isolator is an ideal directional gate, not a resolved Faraday-rotator/polarizer assembly. Magneto-optic dispersion, isolation ratios and damage thresholds are not computed.",
    references: [{"label":"Thorlabs: optical isolator tutorial","url":"https://www.thorlabs.com/catalogPages/682.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("forward-input", "cwlaser", 80, 140, {"beamMode":"line","beamWidth":6}, 0, "forward-input"),
      element("forward-isolator", "isolator", 250, 140, {}, 0, "forward-isolator"),
      element("forward-output", "camera", 422, 140, {"ch":60,"interference":false}, 0, "forward-output"),
      element("reverse-input", "cwlaser", 600, 350, {"beamMode":"line","beamWidth":6}, 180, "reverse-input"),
      element("reverse-isolator", "isolator", 350, 350, {}, 0, "reverse-isolator"),
      element("reverse-output", "camera", 150, 350, {"ch":60,"interference":false}, 180, "reverse-output"),
    ], beams: [] },
  },
  {
    id: "ROUTE-06",
    title: "Dual-polarization coherent receiver",
    summary: "A real PBS separates a 45° 1550 nm signal into H and V channels. Each is mixed with a separately represented local-oscillator feed in its own native 50/50 splitter and collected at two ports.",
    steps: ["Follow both polarization channels to their respective optical mixers.","Set the signal to H polarization and compare extinction of the V signal contribution."],
    limit: "This native scene is the polarization-diverse optical mixing front end. It does not implement a four-phase telecom hybrid, balanced RF electronics, data recovery or shared-LO phase locking.",
    references: [{"label":"Thorlabs: balanced coherent detection application note","url":"https://www.thorlabs.com/images/tabimages/AppHighlight_BalancedPhotodetectors.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("signal", "cwlaser", 80, 200, {"wavelength":1550,"beamMode":"line","beamWidth":6,"pol":45}, 0, "signal"),
      element("polarization-demux", "pbs", 250, 200, {}, 90, "polarization-demux"),
      element("H-mixer", "bs", 400, 200, {}, 90, "H-mixer"),
      element("H-LO", "cwlaser", 400, 80, {"wavelength":1550,"beamMode":"line","beamWidth":6}, 90, "H-LO"),
      element("H-port-A", "camera", 622, 200, {"ch":60,"interference":false}, 0, "H-port-A"),
      element("H-port-B", "camera", 400, 300, {"ch":60,"interference":false}, 90, "H-port-B"),
      element("V-fold", "mirror", 250, 500, {"length":40}, -45, "V-fold"),
      element("V-mixer", "bs", 400, 500, {}, 90, "V-mixer"),
      element("V-LO", "cwlaser", 400, 380, {"wavelength":1550,"beamMode":"line","beamWidth":6,"pol":90}, 90, "V-LO"),
      element("V-port-A", "camera", 622, 500, {"ch":60,"interference":false}, 0, "V-port-A"),
      element("V-port-B", "camera", 400, 672, {"ch":60,"interference":false}, 90, "V-port-B"),
    ], beams: [] },
  },
  {
    id: "ROUTE-07",
    title: "Prepare circular light and analyze it",
    summary: "A preparation polarizer and quarter-wave plate make circular light. A separate analysis quarter-wave plate converts it back to linear light for a native analyzer and detector.",
    steps: ["Inspect polarization after preparation and analysis separately.","Remove the analysis plate and rotate the analyzer: circular light gives half-power readings."],
    limit: "Native Stokes transformations and Malus-law readings are computed. A calibrated Stokes fit, real plate dispersion and experimental handedness conventions remain external.",
    references: [{"label":"Thorlabs: waveplate tutorial","url":"https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7234&tabname=Tutorial"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamMode":"line","beamWidth":6}, 0, "input"),
      element("preparation-polarizer", "polarizer", 180, 200, {}, 0, "preparation-polarizer"),
      element("preparation-QWP", "qwp", 280, 200, {}, 0, "preparation-QWP"),
      element("analysis-QWP", "qwp", 380, 200, {}, 0, "analysis-QWP"),
      element("analyzer", "polarizer", 480, 200, {"pangle":90}, 0, "analyzer"),
      element("power-readout", "detector", 600, 200, {}, 0, "power-readout"),
    ], beams: [] },
  },
  {
    id: "ROUTE-08",
    title: "90/10 sample and monitor split",
    summary: "A 532 nm beam sends 90% through a sample with 50% excitation transmission and 10% to an independent reference photodiode.",
    steps: ["Compare sample/reference power ratio, nominally 4.5 for the chosen transmissions.","Change source power and verify that both readings scale while their ratio stays fixed."],
    limit: "The traced model shows relative branch power and linear transmission; shot noise, electronics and calibrated normalization are not included.",
    references: [{"label":"Edmund Optics: beamsplitter operation","url":"https://www.edmundoptics.eu/knowledge-center/application-notes/optics/what-are-beamsplitters"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamMode":"line"}, 0, "input"),
      element("splitter", "bs", 300, 200, {"ratio":0.9}, 90, "splitter"),
      element("sample", "sample", 450, 200, {"transmission":0.5}, 90, "sample"),
      element("signal", "detector", 650, 200, {}, 0, "signal"),
      element("reference", "detector", 300, 400, {}, 90, "reference"),
    ], beams: [] },
  },
  {
    id: "FIELD-01",
    title: "Mach–Zehnder phase measurement",
    summary: "A real two-splitter Mach–Zehnder uses two folded 200 mm arms and a native phase plate. Two camera ports inspect the coherent recombination.",
    steps: ["Compare the complementary port profiles.","Set the phase-plate optical path to 0.266 µm at 532 nm and inspect the changed interference."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred.",
    references: [{"label":"MIT: interferometers lecture","url":"https://ocw.mit.edu/courses/2-71-optics-spring-2009/resources/mit2_71s09_lec15/"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":6}, 0, "input"),
      element("MZ-split", "bs", 250, 200, {}, 90, "MZ-split"),
      element("MZ-upper-fold", "mirror", 450, 200, {"length":50}, 135, "MZ-upper-fold"),
      element("MZ-lower-fold", "mirror", 250, 400, {"length":50}, 315, "MZ-lower-fold"),
      element("MZ-phase-bias", "phaseplate", 350, 200, {"opdUm":0,"aperture":60}, 0, "MZ-phase-bias"),
      element("MZ-combine", "bs", 450, 400, {}, 90, "MZ-combine"),
      element("MZ-port-A", "camera", 572, 400, {"ch":60}, 0, "MZ-port-A"),
      element("MZ-port-B", "camera", 450, 522, {"ch":60}, 90, "MZ-port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-02",
    title: "Point-diffraction common-path reference",
    summary: "A focused field crosses a pinhole reference mask: a small spatially filtered component supplies the reference and the remaining field carries specimen phase.",
    steps: ["Identify where the reference is generated from the measured field.","Compare common downstream disturbances with disturbances before the pinhole reference formation."],
    limit: "No pinhole diffraction or common-path phase reconstruction is computed; a single aperture ray model is insufficient.",
    references: [{"label":"Smartt and Steel: theory and application of point-diffraction interferometers","url":"https://doi.org/10.7567/JJAPS.14S1.351"}],
    mode: "unavailable",
    unavailableReason: "The registry slit clips geometrical rays but does not diffract light into a new coherent spherical reference wave. That pinhole-generated reference is indispensable to this point-diffraction common-path interferometer.",
  },
  {
    id: "FIELD-03",
    title: "Triangular Sagnac loop",
    summary: "A real beamsplitter and two mirrors form a triangular counterpropagating loop. The two directions visit the same mirrors in opposite order and recombine at a camera. A separate native pickoff collects the bright return port away from the laser input.",
    steps: ["Follow clockwise and counterclockwise paths through both mirrors.","Move one loop mirror to inspect loss of spatial recombination."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred. The scene is stationary; Earth rotation and Sagnac gyro phase are not computed.",
    references: [{"label":"Migdall et al., NIST: fiber Sagnac experimental topology","url":"https://physics.nist.gov/Divisions/Div844/publications/migdall/TomographyfiberentanglementOptExpress.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {}, 0, "input"),
      element("return-pickoff", "bs", 150, 200, {}, 90, "return-pickoff"),
      element("loop-splitter", "bs", 250, 200, {}, 25.6700959, "loop-splitter"),
      element("right-loop-mirror", "mirror", 550, 200, {"length":50}, -160.6700959, "right-loop-mirror"),
      element("upper-loop-mirror", "mirror", 400, 80, {"length":50}, 90, "upper-loop-mirror"),
      element("return-port", "camera", 150, 280, {"ch":60}, 141.3401918, "return-port"),
      element("bright-return", "camera", 150, 80, {"ch":60}, -90, "bright-return"),
      element("unused-pickoff-port", "beamdump", 150, 250, {"aperture":30}, 90, "unused-pickoff-port"),
    ], beams: [] },
  },
  {
    id: "FIELD-04",
    title: "Lateral shear collimation test",
    summary: "A native Mach–Zehnder bench produces two laterally displaced copies of a test beam by shifting one folding mirror 1 mm. Its two cameras inspect overlap and interference.",
    steps: ["Compare the displaced branch with the aligned branch at recombination.","Restore the folding mirror to x = 450 mm and compare the overlapped profile."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred. This is a real mirror-generated lateral-shear bench; the registry does not implement the two coherent surface reflections of a commercial wedged shear plate.",
    references: [{"label":"Thorlabs: shearing interferometer catalogue and operation","url":"https://www.thorlabs.com/images/Catalog/V21/V21_7_LightAnalysis.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":10}, 0, "input"),
      element("shear-split", "bs", 250, 200, {}, 90, "shear-split"),
      element("shear-upper-fold", "mirror", 451, 200, {"length":50}, 135, "shear-upper-fold"),
      element("shear-lower-fold", "mirror", 250, 400, {"length":50}, 315, "shear-lower-fold"),
      element("shear-phase-bias", "phaseplate", 350, 200, {"opdUm":0,"aperture":60}, 0, "shear-phase-bias"),
      element("shear-combine", "bs", 450, 400, {}, 90, "shear-combine"),
      element("shear-port-A", "camera", 572, 400, {"ch":60}, 0, "shear-port-A"),
      element("shear-port-B", "camera", 450, 522, {"ch":60}, 90, "shear-port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-05",
    title: "Differential balanced photodetection",
    summary: "An actual Mach–Zehnder supplies two complementary native camera readouts. Their collected optical signals can be compared as the input to an external balanced detector.",
    steps: ["Compare the two collected powers before subtracting them externally.","Change the phase bias and inspect the complementary signal change."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred. Cameras supply optical readouts; no 0.8 A/W photodiode conversion or difference amplifier is implemented.",
    references: [{"label":"Thorlabs: balanced coherent detection application note","url":"https://www.thorlabs.com/images/tabimages/AppHighlight_BalancedPhotodetectors.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":6}, 0, "input"),
      element("balanced-split", "bs", 250, 200, {}, 90, "balanced-split"),
      element("balanced-upper-fold", "mirror", 450, 200, {"length":50}, 135, "balanced-upper-fold"),
      element("balanced-lower-fold", "mirror", 250, 400, {"length":50}, 315, "balanced-lower-fold"),
      element("balanced-phase-bias", "phaseplate", 350, 200, {"opdUm":0,"aperture":60}, 0, "balanced-phase-bias"),
      element("balanced-combine", "bs", 450, 400, {}, 90, "balanced-combine"),
      element("balanced-port-A", "camera", 572, 400, {"ch":60}, 0, "balanced-port-A"),
      element("balanced-port-B", "camera", 450, 522, {"ch":60}, 90, "balanced-port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-06",
    title: "10 MHz heterodyne receiver",
    summary: "Two real native laser sources enter orthogonal ports of a 50/50 optical coupler. A nominal 10 MHz optical-frequency offset is encoded by a roughly 0.00008014 nm wavelength separation near 1550 nm.",
    steps: ["Inspect both source contributions at the output ports.","Block either source and compare collected optical power."],
    limit: "The optical heterodyne mixing layout and branch powers are traced. Static camera readout does not simulate a 10 MHz temporal beat, balanced RF receiver or coherent phase locking of independent lasers.",
    references: [{"label":"Thorlabs: balanced coherent detection application note","url":"https://www.thorlabs.com/images/tabimages/AppHighlight_BalancedPhotodetectors.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("signal", "cwlaser", 80, 200, {"wavelength":1550,"avgPowerW":0.001,"beamMode":"line","beamWidth":6}, 0, "signal"),
      element("LO", "cwlaser", 350, 80, {"wavelength":1550.00008014,"avgPowerW":0.01,"beamMode":"line","beamWidth":6}, 90, "LO"),
      element("mixing-coupler", "bs", 350, 200, {}, 90, "mixing-coupler"),
      element("port-A", "camera", 572, 200, {"ch":60,"interference":false}, 0, "port-A"),
      element("port-B", "camera", 350, 422, {"ch":60,"interference":false}, 90, "port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-07",
    title: "90° optical hybrid I/Q readout",
    summary: "A common coherent input feeds two real Mach–Zehnder analyzers. A 0.133 µm optical-path bias in the second analyzer introduces a nominal quarter-cycle phase at 532 nm and supplies four camera ports.",
    steps: ["Compare the two analyzer pairs and their distinct phase biases.","Change a common test phase by editing both arm plates equally, retaining the quarter-wave offset."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred. This is a bench quadrature analyzer; complex-field fitting, matched balanced electronics and commercial integrated hybrids are not implemented.",
    references: [{"label":"Thorlabs: balanced coherent detection application note","url":"https://www.thorlabs.com/images/tabimages/AppHighlight_BalancedPhotodetectors.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"beamWidth":6}, 0, "input"),
      element("quadrature-feed", "bs", 200, 200, {}, 90, "quadrature-feed"),
      element("I-split", "bs", 400, 200, {}, 90, "I-split"),
      element("I-upper-fold", "mirror", 600, 200, {"length":50}, 135, "I-upper-fold"),
      element("I-lower-fold", "mirror", 400, 400, {"length":50}, 315, "I-lower-fold"),
      element("I-phase-bias", "phaseplate", 500, 200, {"opdUm":0,"aperture":60}, 0, "I-phase-bias"),
      element("I-combine", "bs", 600, 400, {}, 90, "I-combine"),
      element("I-port-A", "camera", 722, 400, {"ch":60}, 0, "I-port-A"),
      element("I-port-B", "camera", 600, 522, {"ch":60}, 90, "I-port-B"),
      element("Q-split", "bs", 200, 450, {}, 180, "Q-split"),
      element("Q-upper-fold", "mirror", 200, 650, {"length":50}, 225, "Q-upper-fold"),
      element("Q-lower-fold", "mirror", 0, 450, {"length":50}, 405, "Q-lower-fold"),
      element("Q-phase-bias", "phaseplate", 200, 550, {"opdUm":0.133,"aperture":60}, 90, "Q-phase-bias"),
      element("Q-combine", "bs", 0, 650, {}, 180, "Q-combine"),
      element("Q-port-A", "camera", 2.842170943040401e-14, 772, {"ch":60}, 90, "Q-port-A"),
      element("Q-port-B", "camera", -122, 650, {"ch":60}, 180, "Q-port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-08",
    title: "Spectral-domain OCT layer probe",
    summary: "A native broadband source feeds a Michelson-like sample/reference front end. Two sample interfaces and a reference mirror return light to a native spectral receiver.",
    steps: ["Follow front-interface, back-interface and reference returns separately.","Move the reference mirror and inspect the geometric optical-path change."],
    limit: "This is the actual ray and spectrum collection front end of an OCT arrangement. The native receiver does not calculate a broadband spectral interferogram, k-linearization, depth reconstruction or axial resolution.",
    references: [{"label":"Thorlabs: OCT tutorial","url":"https://www.thorlabs.com/images/pdf/octmanualrev7.pdf"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("broadband-input", "sclaser", 80, 200, {"scMin":815,"scMax":865}, 0, "broadband-input"),
      element("sample-reference-split", "bs", 250, 200, {}, 0, "sample-reference-split"),
      element("reference-mirror", "mirror", 450, 200, {"length":40}, 0, "reference-mirror"),
      element("sample-front-interface", "bs", 250, 80, {"ratio":0.8}, 45, "sample-front-interface"),
      element("sample-back-interface", "mirror", 250, 20, {"length":40}, 90, "sample-back-interface"),
      element("spectral-receiver", "spectrometer", 250, 450, {"aperture":60}, 90, "spectral-receiver"),
    ], beams: [] },
  },
  {
    id: "FIELD-09",
    title: "Two-aperture destructive nuller",
    summary: "A native 3.8 µm bench splits a common coherent beam into two aperture feeds and recombines them with a 1.9 µm optical-path bias. Complementary cameras monitor the nominal null and bright ports.",
    steps: ["Compare biased and unbiased output profiles.","Change the phase bias slightly to inspect residual light at the nominally dark port."],
    limit: "Native ray paths and camera coherent-field readout are computed within the existing scalar/coherence model. No RF electronics, noise, real coating phase, wavefront aberrations or calibrated interferometer sensitivity are inferred. This common-source bench does not simulate a stellar angular field, atmospheric piston, broadband null depth or astronomical contrast.",
    references: [{"label":"Asgard/NOTT authors: nulling interferometer optical design","url":"https://arxiv.org/abs/2402.09013"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("input", "cwlaser", 80, 200, {"wavelength":3800,"beamWidth":6}, 0, "input"),
      element("nuller-split", "bs", 250, 200, {}, 90, "nuller-split"),
      element("nuller-upper-fold", "mirror", 450, 200, {"length":50}, 135, "nuller-upper-fold"),
      element("nuller-lower-fold", "mirror", 250, 400, {"length":50}, 315, "nuller-lower-fold"),
      element("nuller-phase-bias", "phaseplate", 350, 200, {"opdUm":1.9,"aperture":60}, 0, "nuller-phase-bias"),
      element("nuller-combine", "bs", 450, 400, {}, 90, "nuller-combine"),
      element("nuller-port-A", "camera", 572, 400, {"ch":60}, 0, "nuller-port-A"),
      element("nuller-port-B", "camera", 450, 522, {"ch":60}, 90, "nuller-port-B"),
    ], beams: [] },
  },
  {
    id: "FIELD-10",
    title: "Two-telescope coherent aperture combination",
    summary: "Two real afocal aperture-feed relays in a K-band interferometer route a common coherent source to a shared beamsplitter and two camera ports. The native phase plate supplies editable optical path in one feed.",
    steps: ["Follow both native aperture-feed relays into the shared combiner.","Translate one feed lens to inspect loss of collimation and overlap at the two fixed camera planes."],
    limit: "Real native 2D feed and recombination geometry is traced. The current camera coherent-field reconstruction does not recover these lens-transformed feeds, so output powers are geometric ray sums and no fringes or phase-dependent power are computed. There is no sky baseline, atmosphere, fringe tracker or aperture synthesis.",
    references: [{"label":"ESO: GRAVITY instrument subsystems","url":"https://www.eso.org/sci/facilities/paranal/instruments/gravity/inst.html"}],
    mode: "rays",
    scene: { version: 1, elements: [
      element("common-star-proxy", "cwlaser", 80, 200, {"wavelength":2200,"beamWidth":4}, 0, "common-star-proxy"),
      element("apertures-split", "bs", 250, 200, {}, 90, "apertures-split"),
      element("apertures-upper-fold", "mirror", 450, 200, {"length":50}, 135, "apertures-upper-fold"),
      element("apertures-lower-fold", "mirror", 250, 400, {"length":50}, 315, "apertures-lower-fold"),
      element("apertures-phase-bias", "phaseplate", 375, 200, {"opdUm":0,"aperture":60}, 0, "apertures-phase-bias"),
      element("apertures-combine", "bs", 450, 400, {}, 90, "apertures-combine"),
      element("apertures-port-A", "camera", 572, 400, {"ch":60}, 0, "apertures-port-A"),
      element("apertures-port-B", "camera", 450, 522, {"ch":60}, 90, "apertures-port-B"),
      element("feed-A-1", "lens", 310, 200, {"f":20,"dia":20}, 0, "feed-A-1"),
      element("feed-A-2", "lens", 350, 200, {"f":20,"dia":20}, 0, "feed-A-2"),
      element("feed-B-1", "lens", 250, 260, {"f":20,"dia":20}, 90, "feed-B-1"),
      element("feed-B-2", "lens", 250, 300, {"f":20,"dia":20}, 90, "feed-B-2"),
    ], beams: [] },
  },
];
