#!/usr/bin/env python3
"""Regenerate the expected values and the validation report.

    python3 validation/run.py            # write validation/expected/*.json and docs/validation.md
    python3 validation/run.py --check    # exit 1 if either is out of date

Each module under validation/reference/ is an independent implementation of
one model the app ships. Its `cases()` return inputs, expected outputs and a
tolerance; its `MODEL` block says what is checked, against which source, and
inside which scope. test/validation.test.js calls the JavaScript with the
same inputs and asserts agreement. Plain Python only, no dependencies.
"""

import importlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE = os.path.join(ROOT, "validation", "reference")
EXPECTED = os.path.join(ROOT, "validation", "expected")
REPORT = os.path.join(ROOT, "docs", "validation.md")
CONVERGENCE = os.path.join(ROOT, "validation", "expected", "convergence.json")
MODULES = ["sellmeier", "pulse", "argon_capillary", "nlse", "paraxial"]

sys.path.insert(0, REFERENCE)


def build():
    results = []
    for name in MODULES:
        module = importlib.import_module(name)
        results.append({**module.MODEL, "reference_file": f"validation/reference/{name}.py", "cases": module.cases()})
    return results


# Quantitative models the app ships that have no reference check yet. Being
# absent from the table above says nothing about a model's quality -- only
# that nobody has checked it against an independent source. Keeping this list
# accurate is part of adding a model (docs/adding-physics.md).
UNCOVERED = [
    ("OPO signal and idler wavelengths, Manley-Rowe power split and depletion", "sketch/js/parametric.js"),
    ("Supercontinuum spectral range from pump and medium", "sketch/js/parametric.js"),
    ("Sum- and difference-frequency mixing wavelengths and durations", "sketch/js/parametric.js"),
    ("Objective focal length, NA, acceptance angle and pupil relations", "sketch/js/objective.js"),
    ("Acousto-optic deflection angle and efficiency", "sketch/js/acousto-optic.js, sketch/js/aotf.js"),
    ("Grating and prism dispersion as the tracer applies them, including order efficiency", "sketch/js/raytrace.js"),
    ("Filtered-pulse duration: the numerical transform, the assumed-sweep continuum estimate and the decline rules", "sketch/js/pulse-field.js: quadraticPhasePulse; sketch/js/glass.js: filteredPulseDuration"),
    ("Etalon fringe-resolved mean transmission", "sketch/js/raytrace.js: etalonMeanTransmission"),
    ("Sampled-envelope intensity autocorrelation", "sketch/js/pulse-field.js: envelopeAutocorrelation"),
    ("Coherent recombination and camera integration", "sketch/js/raytrace.js, sketch/js/camera-profile.js"),
    ("Aspheric and multi-surface lens-group cardinal points", "sketch/js/asphere.js, sketch/js/lensgroup.js"),
    ("Fluorescence, two-photon and Raman signal yields (qualitative by design)", "sketch/js/raytrace.js"),
]


def convergence_rows(keys):
    """Measured refinement results for one model, from convergence.py.

    The numbers in the report come from that script's output rather than from
    a sentence someone wrote: a claim about convergence is only worth as much
    as the measurement behind it.
    """
    if not os.path.exists(CONVERGENCE):
        return ["- _No convergence study recorded; run `python3 validation/convergence.py`._"]
    with open(CONVERGENCE) as handle:
        study = json.load(handle)
    rows = [s for s in study["studies"] if any(k in s["quantity"] for k in keys)]
    if not rows:
        return ["- _No refinement recorded for this model._"]
    return [
        f"- {s['quantity']}: {s['setting']} → {s['refined']} moves it by "
        f"{s['relativeChange']:.3g} relative ({s['value']:.10g} → {s['refinedValue']:.10g})."
        for s in rows
    ]


def report(results):
    lines = [
        "# Reference checks of the quantitative models",
        "",
        "Generated by `python3 validation/run.py`; do not edit by hand. Each row is a",
        "model that has been checked by `test/validation.test.js` against an",
        "independent implementation under `validation/reference/`, and in several",
        "cases against published measurements. The tolerance is the relative (or,",
        "where marked, absolute) agreement the test demands; the reference files",
        "state the equations, conventions, provenance and error budgets.",
        "",
        "**What a row means.** The app computes the model it says it computes, at the",
        "inputs tested, to the stated tolerance. That is *reference-checked*, not",
        "*experimentally validated*: except where a row cites a published",
        "measurement, these checks compare two evaluations of the same published",
        "theory, and they say nothing about how well that theory matches an",
        "experiment on your bench.",
        "",
        "**What a row does not mean.** It does not mean the app refuses every input",
        "outside the stated scope. Each model's behaviour outside its range is stated",
        "in the table, because it differs: the argon capillary declines, while the",
        "glass catalogue clamps to the edge of its fit and keeps returning a number",
        "(`isWavelengthInGlassRange` reports whether that happened).",
        "",
        "**Coverage is partial.** The models below are checked; the ones listed under",
        "'Not yet checked' are not, and their absence is not a statement about their",
        "quality. See the wiki page of each component for what it models.",
        "",
        "See `docs/adding-physics.md` for how a new model earns a row in this table.",
        "",
        "| Model | App functions | Reference | Cases | Tightest / loosest tolerance | Scope | Outside that scope |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in results:
        tolerances = [t for c in r["cases"] for t in c["tolerance"].values()]
        code = "../" + r["reference_file"].replace(os.sep, "/")
        lines.append(
            f"| **{r['title']}** | `{r['app']}` | {r['reference']} ([code]({code})) "
            f"| {len(r['cases'])} | {min(tolerances):g} / {max(tolerances):g} | {r['scope']} | {r.get('outside_scope', 'not stated')} |"
        )
    lines += ["", "## Not yet checked", "",
              "Quantitative models the app ships with no reference check. Each needs a",
              "reference, a tolerance and an error budget before it can move into the",
              "table above.", ""]
    for title, where in UNCOVERED:
        lines.append(f"- **{title}** — `{where}`")
    lines += ["", "## How each check was made", ""]
    for r in results:
        lines.append(f"### {r['title']}")
        lines.append("")
        for label, key in (("Provenance", "provenance"), ("Cases run", "domain"),
                           ("Method", "convergence"), ("Tolerances", "tolerance_rationale")):
            if r.get(key):
                lines.append(f"- **{label}.** {r[key]}")
        if r.get("convergence_keys"):
            lines.append("- **Measured convergence** (`validation/convergence.py`):")
            for row in convergence_rows(r["convergence_keys"]):
                lines.append(f"  {row}")
        lines.append("")
        lines.append("Sources:")
        lines.append("")
        for c in r["citations"]:
            lines.append(f"- {c}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    results = build()
    os.makedirs(EXPECTED, exist_ok=True)
    stale = []
    outputs = {os.path.join(EXPECTED, f"{r['id']}.json"): json.dumps(r, indent=1, sort_keys=True) + "\n" for r in results}
    outputs[REPORT] = report(results)
    for path, text in outputs.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current == text:
            continue
        stale.append(os.path.relpath(path, ROOT))
        if not check:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(text)
    if check and stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        sys.exit(1)
    print("validation files are current" if not stale else "wrote " + ", ".join(stale))


if __name__ == "__main__":
    main()
