#!/usr/bin/env python3
"""Regenerate the expected values and the validation report.

    python3 validation/run.py            # write validation/expected/*.json and docs/validation.md
    python3 validation/run.py --check    # exit 1 if either is out of date

Each module under validation/reference/ is an independent implementation of
one model the app ships. Its `cases()` return inputs, expected outputs and a
tolerance; its `MODEL` block says what is checked, against which source, and
inside which scope. test/validation.test.js calls the JavaScript with the
same inputs and asserts agreement. Plain Python only, no dependencies.
"""

import importlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE = os.path.join(ROOT, "validation", "reference")
EXPECTED = os.path.join(ROOT, "validation", "expected")
REPORT = os.path.join(ROOT, "docs", "validation.md")
MODULES = ["sellmeier", "pulse", "argon_capillary", "nlse", "paraxial"]

sys.path.insert(0, REFERENCE)


def build():
    results = []
    for name in MODULES:
        module = importlib.import_module(name)
        results.append({**module.MODEL, "reference_file": f"validation/reference/{name}.py", "cases": module.cases()})
    return results


def report(results):
    lines = [
        "# Validation of the quantitative models",
        "",
        "Generated by `python3 validation/run.py`; do not edit by hand. Each row is a",
        "model the app ships, checked by `test/validation.test.js` against an",
        "independent reference implementation under `validation/reference/`. The",
        "tolerance is the relative (or, where marked, absolute) agreement the test",
        "demands; the reference files state the equations, conventions and sources.",
        "",
        "A model listed here is **computed**: the number the app shows is the number",
        "the reference produces, inside the stated scope. Outside that scope the app",
        "reports the quantity as unavailable rather than extrapolating. Models that",
        "are not listed here are qualitative or diagram-only; see the wiki page of",
        "each component and the simulation-scope section of the README.",
        "",
        "See `docs/adding-physics.md` for how a new model earns a row in this table.",
        "",
        "| Model | App functions | Reference | Cases | Tightest / loosest tolerance | Scope |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in results:
        tolerances = [t for c in r["cases"] for t in c["tolerance"].values()]
        lines.append(
            f"| **{r['title']}** | `{r['app']}` | {r['reference']} ([code]({r['reference_file'].replace(os.sep, '/')})) "
            f"| {len(r['cases'])} | {min(tolerances):g} / {max(tolerances):g} | {r['scope']} |"
        )
    lines += ["", "## Sources", ""]
    for r in results:
        lines.append(f"**{r['title']}**")
        lines.append("")
        for c in r["citations"]:
            lines.append(f"- {c}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    results = build()
    os.makedirs(EXPECTED, exist_ok=True)
    stale = []
    outputs = {os.path.join(EXPECTED, f"{r['id']}.json"): json.dumps(r, indent=1, sort_keys=True) + "\n" for r in results}
    outputs[REPORT] = report(results)
    for path, text in outputs.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current == text:
            continue
        stale.append(os.path.relpath(path, ROOT))
        if not check:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(text)
    if check and stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        sys.exit(1)
    print("validation files are current" if not stale else "wrote " + ", ".join(stale))


if __name__ == "__main__":
    main()
